name: metrics-server-mavryk
version: 0.0.1
apiVersion: v2
appVersion: 0.6.4
dependencies:
  - name: metrics-server
    version: 3.11.0
    repository: https://kubernetes-sigs.github.io/metrics-server/
