# generated by datamodel-codegen:
#   filename:  fixMistakenTransfer.json

from __future__ import annotations

from typing import Any, Dict, List, Union

from pydantic import BaseModel, Extra


class TokenItem(BaseModel):
    class Config:
        extra = Extra.forbid

    fa12: str


class Fa2(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenContractAddress: str
    tokenId: str


class TokenItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    fa2: Fa2


class TokenItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    mav: Dict[str, Any]


class TransferListItem(BaseModel):
    class Config:
        extra = Extra.forbid

    to_: str
    amount: str
    token: Union[TokenItem, TokenItem1, TokenItem2]


class FixMistakenTransferParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    targetContractAddress: str
    purpose: str
    transferList: List[TransferListItem]
