# generated by datamodel-codegen:
#   filename:  delegateToSatelliteComplete.json

from __future__ import annotations

from pydantic import BaseModel


class DelegateToSatelliteCompleteParameter(BaseModel):
    __root__: str
