# generated by datamodel-codegen:
#   filename:  delegateToSatellite.json

from __future__ import annotations

from pydantic import BaseModel


class DelegateToSatelliteParameter(BaseModel):
    __root__: str
