# generated by datamodel-codegen:
#   filename:  onStakeChange.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class OnStakeChangeParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    address: str
    nat_0: str
    nat_1: str
