# generated by datamodel-codegen:
#   filename:  onSatelliteRewardPaid.json

from __future__ import annotations

from pydantic import BaseModel


class OnSatelliteRewardPaidParameter(BaseModel):
    __root__: str
