# generated by datamodel-codegen:
#   filename:  onStakeChange.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class OnStakeChangeParameter(BaseModel):
    __root__: List[str]
