# generated by datamodel-codegen:
#   filename:  redelegateSatellite.json

from __future__ import annotations

from pydantic import BaseModel


class RedelegateSatelliteParameter(BaseModel):
    __root__: str
