# generated by datamodel-codegen:
#   filename:  registerAsSatelliteComplete.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class RegisterAsSatelliteCompleteParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    string_0: str
    string_1: str
    string_2: str
    nat_0: str
    nat_1: str
