# generated by datamodel-codegen:
#   filename:  togglePauseDelegateToSatellite.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TogglePauseDelegateToSatelliteParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
