# generated by datamodel-codegen:
#   filename:  togglePauseUnregisterSatellite.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TogglePauseUnregisterSatelliteParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
