# generated by datamodel-codegen:
#   filename:  togglePauseUndelegateSatellite.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TogglePauseUndelegateSatelliteParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
