# generated by datamodel-codegen:
#   filename:  togglePauseRegisterSatellite.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TogglePauseRegisterSatelliteParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
