# generated by datamodel-codegen:
#   filename:  togglePauseDistributeReward.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TogglePauseDistributeRewardParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
