# generated by datamodel-codegen:
#   filename:  undelegateFromSatelliteComplete.json

from __future__ import annotations

from pydantic import BaseModel


class UndelegateFromSatelliteCompleteParameter(BaseModel):
    __root__: str
