# generated by datamodel-codegen:
#   filename:  unregisterAsSatellite.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class UnregisterAsSatelliteParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
