# generated by datamodel-codegen:
#   filename:  updateSatelliteRecord.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class UpdateSatelliteRecordParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    string_0: str
    string_1: str
    string_2: str
    nat: str
