# generated by datamodel-codegen:
#   filename:  updateConfig.json

from __future__ import annotations

from typing import Any, Dict, Union

from pydantic import BaseModel, Extra


class UpdateConfigActionItem(BaseModel):
    class Config:
        extra = Extra.forbid

    configAdminLiquidationFee: Dict[str, Any]


class UpdateConfigActionItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    configCollateralRatio: Dict[str, Any]


class UpdateConfigActionItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    configInterestTreasuryShare: Dict[str, Any]


class UpdateConfigActionItem3(BaseModel):
    class Config:
        extra = Extra.forbid

    configLastCompletedDataMaxDelay: Dict[str, Any]


class UpdateConfigActionItem4(BaseModel):
    class Config:
        extra = Extra.forbid

    configLiquidationDelayInMins: Dict[str, Any]


class UpdateConfigActionItem5(BaseModel):
    class Config:
        extra = Extra.forbid

    configLiquidationFeePercent: Dict[str, Any]


class UpdateConfigActionItem6(BaseModel):
    class Config:
        extra = Extra.forbid

    configLiquidationMaxDuration: Dict[str, Any]


class UpdateConfigActionItem7(BaseModel):
    class Config:
        extra = Extra.forbid

    configLiquidationRatio: Dict[str, Any]


class UpdateConfigActionItem8(BaseModel):
    class Config:
        extra = Extra.forbid

    configMaxVaultLiqPercent: Dict[str, Any]


class UpdateConfigActionItem9(BaseModel):
    class Config:
        extra = Extra.forbid

    configMinLoanFeeTreasuryShare: Dict[str, Any]


class UpdateConfigActionItem10(BaseModel):
    class Config:
        extra = Extra.forbid

    configMinimumLoanFeePercent: Dict[str, Any]


class UpdateConfigParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    updateConfigNewValue: str
    updateConfigAction: Union[
        UpdateConfigActionItem,
        UpdateConfigActionItem1,
        UpdateConfigActionItem2,
        UpdateConfigActionItem3,
        UpdateConfigActionItem4,
        UpdateConfigActionItem5,
        UpdateConfigActionItem6,
        UpdateConfigActionItem7,
        UpdateConfigActionItem8,
        UpdateConfigActionItem9,
        UpdateConfigActionItem10,
    ]
