# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict, Optional

from pydantic import BaseModel, Extra


class BreakGlassConfig(BaseModel):
    class Config:
        extra = Extra.forbid

    compoundIsPaused: bool
    stakeIsPaused: bool
    unstakeIsPaused: bool


class UserStakeBalanceLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    balance: str
    participationFeesPerShare: str


class DoormanStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    accumulatedFeesPerShare: str
    admin: str
    breakGlassConfig: BreakGlassConfig
    generalContracts: Dict[str, str]
    logExitFee: str
    logFinalAmount: str
    minMvkAmount: str
    mvkTokenAddress: str
    stakedMvkTotalSupply: str
    tempClaimAmount: Optional[str]
    tempClaimDelegator: Optional[str]
    tempClaimForceTransfer: Optional[bool]
    tempUnstakeAmount: Optional[str]
    unclaimedRewards: str
    userStakeBalanceLedger: Dict[str, UserStakeBalanceLedger]
    whitelistContracts: Dict[str, str]
