# generated by datamodel-codegen:
#   filename:  voteForRequest.json

from __future__ import annotations

from typing import Any, Dict, Union

from pydantic import BaseModel, Extra, Field


class VoteItem(BaseModel):
    class Config:
        extra = Extra.forbid

    nay: Dict[str, Any]


class VoteItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    pass_: Dict[str, Any] = Field(..., alias='pass')


class VoteItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    yay: Dict[str, Any]


class VoteForRequestParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    requestId: str
    vote: Union[VoteItem, VoteItem1, VoteItem2]
