---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: promscale
  namespace: kube-prometheus-stack
  labels:
    release: 'prod'
spec:
  endpoints:
    - interval: 30s
      port: metrics-port
      path: /metrics
  namespaceSelector:
    matchNames:
      - promscale
  selector:
    matchLabels:
      app: prod-promscale
      release: prod
