export const GOVERNANCE_STORAGE_QUERY = `
  query GetGovernanceStorageQuery {
    governance {
      address
      blocks_per_minute
      blocks_per_proposal_round
      blocks_per_timelock_round
      blocks_per_voting_round
      current_cycle_end_level
      current_round
      current_round_end_level
      current_round_start_level
      max_proposal_per_delegate
      minimum_stake_req_percentage
      next_proposal_id
      proposal_round_vote_percentage
      proposal_round_vote_required
      voting_power_ratio
      success_reward
      current_blocks_per_proposal_round
      current_blocks_per_timelock_round
      current_blocks_per_voting_round
      current_cycle_total_voters_reward
      current_round_highest_voted_proposal_id
      cycle_counter
      cycle_voters_reward
      governance_proxy_address
      proposal_invoice_max_length
      proposal_metadata_title_max_length
      proposal_description_max_length
      proposal_source_code_max_length
      proposal_submission_fee_mutez
      proposal_title_max_length
      quorum_mvk_total
      quorum_percentage
      timelock_proposal_id
    }
    governance_financial_request_record {
      approve_vote_total
      executed
      disapprove_vote_total
      expiration_datetime
      id
      ready
      request_purpose
      request_type
      requested_datetime
      smvk_percentage_for_approval
      requester_id
      smvk_required_for_approval
      snapshot_smvk_total_supply
      status
      token_amount
      token_contract_address
      token_id
      token_name
      treasury_id
      votes {
        governance_financial_request_id
        id
        timestamp
        vote
        voter_id
        voting_power
      }
      governance_financial_id
    }
    governance_proposal_record {
      abstain_mvk_total
      current_cycle_end_level
      current_cycle_start_level
      current_round_proposal
      cycle
      description
      down_vote_mvk_total
      id
      executed
      invoice
      locked
      min_proposal_round_vote_pct
      pass_vote_mvk_total
      min_quorum_percentage
      min_quorum_mvk_total
      min_proposal_round_vote_req
      proposer_id
      quorum_mvk_total
      source_code
      start_datetime
      status
      success_reward
      title
      votes {
        current_round_vote
        governance_proposal_record_id
        id
        round
        vote
        voter_id
        voting_power
      }
      abstain_vote_count
      down_vote_count
      execution_counter
      governance_id
      payment_processed
      pass_vote_count
      quorum_vote_count
      up_vote_count
      up_vote_mvk_total
      proposal_data {
        bytes
        governance_proposal_record_id
        id
        record_internal_id
        title
      }
      proposal_payments {
        governance_proposal_record_id
        id
        record_internal_id
        title
        to__id
        token_address
        token_amount
        token_id
        token_standard
      }
    }
  }
`

export const GOVERNANCE_STORAGE_QUERY_NAME = 'GetGovernanceStorageQuery'
export const GOVERNANCE_STORAGE_QUERY_VARIABLE = {}
