# generated by datamodel-codegen:
#   filename:  togglePauseEntrypoint.json

from __future__ import annotations

from typing import Any, Dict, Union

from pydantic import BaseModel, Extra


class TargetEntrypointItem(BaseModel):
    class Config:
        extra = Extra.forbid

    createAggregator: bool


class TargetEntrypointItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    distributeRewardStakedMvn: bool


class TargetEntrypointItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    distributeRewardMvrk: bool


class TargetEntrypointItem3(BaseModel):
    class Config:
        extra = Extra.forbid

    trackAggregator: bool


class TargetEntrypointItem4(BaseModel):
    class Config:
        extra = Extra.forbid

    untrackAggregator: bool


class TogglePauseEntrypointParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    targetEntrypoint: Union[
        TargetEntrypointItem,
        TargetEntrypointItem1,
        TargetEntrypointItem2,
        TargetEntrypointItem3,
        TargetEntrypointItem4,
    ]
    empty: Dict[str, Any]
