# generated by datamodel-codegen:
#   filename:  addToWhitelist.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class AddToWhitelistParameter(BaseModel):
    __root__: List[str]
