# generated by datamodel-codegen:
#   filename:  buyTokens.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class BuyTokensParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    amount: str
    buyOption: str
