# generated by datamodel-codegen:
#   filename:  closeSale.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class CloseSaleParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
