# generated by datamodel-codegen:
#   filename:  pauseSale.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class PauseSaleParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
