# generated by datamodel-codegen:
#   filename:  removeFromWhitelist.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class RemoveFromWhitelistParameter(BaseModel):
    __root__: List[str]
