# generated by datamodel-codegen:
#   filename:  setWhitelistTimestamp.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class SetWhitelistTimestampParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    whitelistStartTimestamp: str
    whitelistEndTimestamp: str
