# generated by datamodel-codegen:
#   filename:  startSale.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class StartSaleParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
