# generated by datamodel-codegen:
#   filename:  updateConfig.json

from __future__ import annotations

from typing import Any, Dict, Union

from pydantic import BaseModel, Extra


class UpdateConfigActionItem(BaseModel):
    class Config:
        extra = Extra.forbid

    configMaxAmountCap: str


class UpdateConfigActionItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    configMaxAmountPerWalletTotal: str


class UpdateConfigActionItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    configMinMvkAmount: str


class UpdateConfigActionItem3(BaseModel):
    class Config:
        extra = Extra.forbid

    configTokenXtzPrice: str


class UpdateConfigActionItem4(BaseModel):
    class Config:
        extra = Extra.forbid

    configVestingPeriodDurationSec: Dict[str, Any]


class UpdateConfigActionItem5(BaseModel):
    class Config:
        extra = Extra.forbid

    configVestingPeriods: str


class UpdateConfigActionItem6(BaseModel):
    class Config:
        extra = Extra.forbid

    configWhitelistMaxAmountTotal: str


class UpdateConfigParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    updateConfigNewValue: str
    updateConfigAction: Union[
        UpdateConfigActionItem,
        UpdateConfigActionItem1,
        UpdateConfigActionItem2,
        UpdateConfigActionItem3,
        UpdateConfigActionItem4,
        UpdateConfigActionItem5,
        UpdateConfigActionItem6,
    ]
