# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, Extra


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    decimals: str
    numberBlocksDelay: str
    deviationTriggerBanDuration: str
    perThousandDeviationTrigger: str
    percentOracleThreshold: str
    requestRateDeviationDepositFee: str
    deviationRewardStakedMvk: str
    deviationRewardAmountXtz: str
    rewardAmountStakedMvk: str
    rewardAmountXtz: str


class BreakGlassConfig(BaseModel):
    class Config:
        extra = Extra.forbid

    requestRateUpdateIsPaused: bool
    requestRateUpdateDeviationIsPaused: bool
    setObservationCommitIsPaused: bool
    setObservationRevealIsPaused: bool
    withdrawRewardXtzIsPaused: bool
    withdrawRewardStakedMvkIsPaused: bool


class DeviationTriggerInfos(BaseModel):
    class Config:
        extra = Extra.forbid

    oracleAddress: str
    roundPrice: str


class LastCompletedRoundPrice(BaseModel):
    class Config:
        extra = Extra.forbid

    round: str
    price: str
    percentOracleResponse: str
    priceDateTime: str


class AggregatorStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    metadata: Dict[str, str]
    name: str
    config: Config
    breakGlassConfig: BreakGlassConfig
    maintainer: str
    mvkTokenAddress: str
    governanceAddress: str
    whitelistContracts: Dict[str, str]
    generalContracts: Dict[str, str]
    round: str
    roundStart: str
    switchBlock: str
    oracleAddresses: Dict[str, bool]
    deviationTriggerInfos: DeviationTriggerInfos
    lastCompletedRoundPrice: LastCompletedRoundPrice
    observationCommits: Dict[str, str]
    observationReveals: Dict[str, str]
    deviationTriggerBan: Dict[str, str]
    oracleRewardStakedMvk: Dict[str, str]
    oracleRewardXtz: Dict[str, str]
    lambdaLedger: Dict[str, str]
