# generated by datamodel-codegen:
#   filename:  tezos_storage.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, Extra


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    decimals: str
    alphaPercentPerThousand: str
    percentOracleThreshold: str
    heartBeatSeconds: str
    rewardAmountStakedMvk: str
    rewardAmountXtz: str


class BreakGlassConfig(BaseModel):
    class Config:
        extra = Extra.forbid

    updateDataIsPaused: bool
    withdrawRewardXtzIsPaused: bool
    withdrawRewardStakedMvkIsPaused: bool


class OracleLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    oraclePublicKey: str
    oraclePeerId: str


class LastCompletedData(BaseModel):
    class Config:
        extra = Extra.forbid

    round: str
    epoch: str
    data: str
    percentOracleResponse: str
    lastUpdatedAt: str


class AggregatorStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    metadata: Dict[str, str]
    name: str
    config: Config
    breakGlassConfig: BreakGlassConfig
    mvkTokenAddress: str
    governanceAddress: str
    whitelistContracts: Dict[str, str]
    generalContracts: Dict[str, str]
    oracleLedger: Dict[str, OracleLedger]
    lastCompletedData: LastCompletedData
    oracleRewardStakedMvk: Dict[str, str]
    oracleRewardXtz: Dict[str, str]
    lambdaLedger: Dict[str, str]
