# generated by datamodel-codegen:
<<<<<<< HEAD
#   filename:  exit.json
=======
#   filename:  default.json
>>>>>>> 63661dace (handlers refactored for dipdup 7)

from __future__ import annotations

from pydantic import BaseModel, Extra


<<<<<<< HEAD
class ExitParameter(BaseModel):
=======
class DefaultParameter(BaseModel):
>>>>>>> 63661dace (handlers refactored for dipdup 7)
    pass

    class Config:
        extra = Extra.forbid
