# generated by datamodel-codegen:
#   filename:  tezos_storage.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, Extra


class MvnFaucetStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    amountPerUser: str
    metadata: Dict[str, str]
    mvnTokenAddress: str
    requesters: Dict[str, Dict[str, Any]]
