# generated by datamodel-codegen:
#   filename:  compound.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class CompoundParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
