# generated by datamodel-codegen:
#   filename:  farmClaimComplete.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class FarmClaimCompleteParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    address: str
    nat: str
    bool: bool
