# generated by datamodel-codegen:
#   filename:  farmClaim.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class FarmClaimParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    address: str
    nat: str
    bool: bool
