# generated by datamodel-codegen:
#   filename:  onVaultLiquidateStakedMvk.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class OnVaultLiquidateStakedMvkParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    vaultOwner: str
    vaultAddress: str
    liquidator: str
    liquidatedAmount: str
