# generated by datamodel-codegen:
#   filename:  onVaultWithdrawStakedMvk.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class OnVaultWithdrawStakedMvkParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    vaultOwner: str
    vaultAddress: str
    withdrawAmount: str
