# generated by datamodel-codegen:
#   filename:  togglePauseFarmClaim.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TogglePauseFarmClaimParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
