# generated by datamodel-codegen:
#   filename:  togglePauseStake.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TogglePauseStakeParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
