# generated by datamodel-codegen:
#   filename:  togglePauseCompound.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TogglePauseCompoundParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
