# generated by datamodel-codegen:
#   filename:  togglePauseUnstake.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TogglePauseUnstakeParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
