# generated by datamodel-codegen:
#   filename:  unstakeComplete.json

from __future__ import annotations

from pydantic import BaseModel


class UnstakeCompleteParameter(BaseModel):
    __root__: str
