# generated by datamodel-codegen:
#   filename:  updateMinMvkAmount.json

from __future__ import annotations

from pydantic import BaseModel


class UpdateMinMvkAmountParameter(BaseModel):
    __root__: str
