# generated by datamodel-codegen:
#   filename:  setBaker.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class SetBakerParameter(BaseModel):
    __root__: Optional[str]
