# generated by datamodel-codegen:
#   filename:  updateDepositor.json

from __future__ import annotations

from typing import Any, Dict, Union

from pydantic import BaseModel, Extra


class AllowanceItem(BaseModel):
    class Config:
        extra = Extra.forbid

    any: bool


class Whitelist(BaseModel):
    class Config:
        extra = Extra.forbid

    bool: bool
    address: str


class AllowanceItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    whitelist: Whitelist


class UpdateDepositorParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    allowance: Union[AllowanceItem, AllowanceItem1]
    empty: Dict[str, Any]
