# generated by datamodel-codegen:
#   filename:  updateDepositor.json

from __future__ import annotations

from typing import Any, Dict, Union

from pydantic import BaseModel, Extra


class AllowAccount(BaseModel):
    class Config:
        extra = Extra.forbid

    bool: bool
    address: str


class AllowanceItem(BaseModel):
    class Config:
        extra = Extra.forbid

    allowAccount: AllowAccount


class AllowanceItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    allowAny: bool


class UpdateDepositorParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    allowance: Union[AllowanceItem, AllowanceItem1]
    empty: Dict[str, Any]
