# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Any, Dict, List, Union

from pydantic import BaseModel, Extra, Field


class AggregatorPair(BaseModel):
    class Config:
        extra = Extra.forbid

    string_0: str
    string_1: str


class AggregatorLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    aggregatorPair: AggregatorPair
    status: str
    createdTimestamp: str
    oracles: List[str]


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    governanceSatelliteApprovalPercentage: str
    governanceSatelliteDurationInDays: str
    governancePurposeMaxLength: str


class VoteItem(BaseModel):
    class Config:
        extra = Extra.forbid

    nay: Dict[str, Any]


class VoteItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    pass_: Dict[str, Any] = Field(..., alias='pass')


class VoteItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    yay: Dict[str, Any]


class Voters(BaseModel):
    class Config:
        extra = Extra.forbid

    vote: Union[VoteItem, VoteItem1, VoteItem2]
    totalVotingPower: str
    timeVoted: str


class GovernanceSatelliteActionLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    initiator: str
    status: bool
    executed: bool
    governanceType: str
    governancePurpose: str
    voters: Dict[str, Voters]
    addressMap: Dict[str, str]
    stringMap: Dict[str, str]
    natMap: Dict[str, str]
    yayVoteStakedMvkTotal: str
    nayVoteStakedMvkTotal: str
    passVoteStakedMvkTotal: str
    snapshotStakedMvkTotalSupply: str
    stakedMvkPercentageForApproval: str
    stakedMvkRequiredForApproval: str
    startDateTime: str
    expiryDateTime: str


class GovernanceSatelliteSnapshotLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    totalStakedMvkBalance: str
    totalDelegatedAmount: str
    totalVotingPower: str


class AggregatorPair1(BaseModel):
    class Config:
        extra = Extra.forbid

    string_0: str
    string_1: str


class AggregatorPairs(BaseModel):
    class Config:
        extra = Extra.forbid

    aggregatorPair: AggregatorPair1
    aggregatorAddress: str
    startDateTime: str


class SatelliteOracleLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    aggregatorsSubscribed: str
    aggregatorPairs: Dict[str, AggregatorPairs]


class GovernanceSatelliteStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    aggregatorLedger: Dict[str, AggregatorLedger]
    config: Config
    generalContracts: Dict[str, str]
    governanceAddress: str
    governanceSatelliteActionLedger: Dict[str, GovernanceSatelliteActionLedger]
    governanceSatelliteCounter: str
    governanceSatelliteSnapshotLedger: Dict[
        str, Dict[str, GovernanceSatelliteSnapshotLedger]
    ]
    lambdaLedger: Dict[str, str]
    metadata: Dict[str, str]
    mvkTokenAddress: str
    satelliteOracleLedger: Dict[str, SatelliteOracleLedger]
    whitelistContracts: Dict[str, str]
