# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Any, Dict, List, Union

from pydantic import BaseModel, Extra, Field


class AggregatorPair(BaseModel):
    class Config:
        extra = Extra.forbid

    string_0: str
    string_1: str


class AggregatorLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    aggregatorPair: AggregatorPair
    status: str
    createdTimestamp: str
    oracles: List[str]


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    governanceSatelliteApprovalPercentage: str
    governanceSatelliteDurationInDays: str
    governancePurposeMaxLength: str
    maxActionsPerSatellite: str


class TokenItem(BaseModel):
    class Config:
        extra = Extra.forbid

    fa12: str


class Fa2(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenContractAddress: str
    tokenId: str


class TokenItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    fa2: Fa2


class TokenItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    tez: Dict[str, Any]


class TransferListItem(BaseModel):
    class Config:
        extra = Extra.forbid

    to_: str
    amount: str
    token: Union[TokenItem, TokenItem1, TokenItem2]


class GovernanceSatelliteActionLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    initiator: str
    status: bool
    executed: bool
    governanceType: str
    governancePurpose: str
    voters: List[str]
    addressMap: Dict[str, str]
    stringMap: Dict[str, str]
    natMap: Dict[str, str]
    transferList: List[TransferListItem]
    yayVoteStakedMvkTotal: str
    nayVoteStakedMvkTotal: str
    passVoteStakedMvkTotal: str
    snapshotStakedMvkTotalSupply: str
    stakedMvkPercentageForApproval: str
    stakedMvkRequiredForApproval: str
    startDateTime: str
    expiryDateTime: str


class Key(BaseModel):
    class Config:
        extra = Extra.forbid

    nat: str
    address: str


class ValueItem(BaseModel):
    class Config:
        extra = Extra.forbid

    nay: Dict[str, Any]


class ValueItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    pass_: Dict[str, Any] = Field(..., alias='pass')


class ValueItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    yay: Dict[str, Any]


class GovernanceSatelliteVoter(BaseModel):
    class Config:
        extra = Extra.forbid

    key: Key
    value: Union[ValueItem, ValueItem1, ValueItem2]


class AggregatorPair1(BaseModel):
    class Config:
        extra = Extra.forbid

    string_0: str
    string_1: str


class AggregatorPairs(BaseModel):
    class Config:
        extra = Extra.forbid

    aggregatorPair: AggregatorPair1
    aggregatorAddress: str
    startDateTime: str


class SatelliteOracleLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    aggregatorsSubscribed: str
    aggregatorPairs: Dict[str, AggregatorPairs]


class GovernanceSatelliteStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    aggregatorLedger: Dict[str, AggregatorLedger]
    config: Config
    cycleActionsInitiators: Dict[str, List[str]]
    generalContracts: Dict[str, str]
    governanceAddress: str
    governanceCycleSnapshot: str
    governanceSatelliteActionLedger: Dict[str, GovernanceSatelliteActionLedger]
    governanceSatelliteCounter: str
    governanceSatelliteVoters: List[GovernanceSatelliteVoter]
    lambdaLedger: Dict[str, str]
    metadata: Dict[str, str]
    mvkTokenAddress: str
    satelliteOracleLedger: Dict[str, SatelliteOracleLedger]
    whitelistContracts: Dict[str, str]
