---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle
  labels:
    app: oracle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle
  template:
    metadata:
      labels:
        app: oracle
    spec:
      imagePullSecrets:
        - name: '{{ $.Values.image.pullSecret }}'
      containers:
        {{ range $key, $value := .Values.oracles }}
        - name: oracle-{{ $key }}
          env:
          {{- range $value.env }}
            - name: {{ .name }}
              {{- if ((.value))}}
              value: "{{.value}}"
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .valueFrom.secretKeyRef.name }}
                  key: {{ .valueFrom.secretKeyRef.key }}
              {{- end }}
          {{- end }}
            - name: TEZOS_POLLING_INTERVAL_MILLISECONDS
              value: '2000'
            - name: RPC_URL
              value: '{{ $value.rpcUrl }}'
            - name: P2P_BOOTSTRAP_PEERS
              value: '{{ include "p2pBootstrapPeers" (list $.Values.oracles $value.p2p.peerId) }}'
            - name: P2P_LISTEN_ADDRESS
              value: '0.0.0.0'
            - name: P2P_LISTEN_PORT
              value: '{{ $value.p2p.listenPort }}'
            - name: P2P_PEER_ID
              value: '{{ $value.p2p.peerId }}'
            - name: P2P_PEER_PUBLIC_KEY
              value: '{{ $value.p2p.peerPublicKey }}'
            - name: P2P_PEER_PRIVATE_KEY
              value: '{{ $value.p2p.peerPrivateKey }}'
            - name: TEZOS_ADDRESS
              value: '{{ $value.tezos.address }}'
            - name: TEZOS_PUBLIC_KEY
              value: '{{ $value.tezos.publicKey }}'
            - name: TEZOS_SECRET_KEY
              value: '{{ $value.tezos.secretKey }}'
            - name: AGGREGATOR_SMART_CONTRACT_ADDRESSES
              value: '{{ join "," $.Values.aggregatorsAddresses }}'
            - name: ALPHAVANTAGE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $value.alphavantage.secretName }}
                  key: {{ $value.alphavantage.key }}
            - name: MESSARI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $value.messari.secretName }}
                  key: {{ $value.messari.key }}
            - name: LOG_LEVEL
              value: 'debug'
            - name: USE_FAKE_DATA
              value: 'false'
          image: '{{ $.Values.image.registry }}/{{ $.Values.image.repository }}:{{ $.Values.image.tag }}'
          imagePullPolicy: '{{ $.Values.image.pullPolicy }}'
        {{ end }}
