{{ range $key, $value := .Values.oracles }}
---
apiVersion: v1
kind: Service
metadata:
  name: oracle-{{ $key }}
  labels:
    app: oracle-{{ $key }}
spec:
  clusterIP: None
  ports:
    - name: p2p
      port: 23456
      protocol: TCP
      targetPort: p2p
  selector:
    app: oracle-{{ $key }}
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oracle-{{ $key }}
  labels:
    app: oracle-{{ $key }}
spec:
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: oracle-{{ $key }}
  serviceName: oracle-{{ $key }}
  template:
    volumeClaimTemplates:
    metadata:
      labels:
        app: oracle-{{ $key }}
    spec:
      imagePullSecrets:
          - name: '{{ $.Values.image.pullSecret }}'
      containers:
        - name: oracle
          env:
          {{- range $value.env }}
            - name: {{ .name }}
              {{- if ((.value))}}
              value: "{{.value}}"
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .valueFrom.secretKeyRef.name }}
                  key: {{ .valueFrom.secretKeyRef.key }}
              {{- end }}
          {{- end }}
            - name: TEZOS_POLLING_INTERVAL_MILLISECONDS
              value: '2000'
            - name: SIGNER_URL
              value: 'http://signatory.mavryk-oracles.svc.cluster.local:6732'
            - name: RPC_URL
              value: '{{ $value.rpcUrl }}'
            - name: P2P_BOOTSTRAP_PEERS
              value: '{{ include "p2pBootstrapPeers" (list $.Values.oracles $value.p2p.peerId) }}'
            - name: P2P_PEER_ID
              value: '{{ $value.p2p.peerId }}'
            - name: P2P_PEER_PUBLIC_KEY
              value: '{{ $value.p2p.peerPublicKey }}'
            - name: P2P_PEER_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $value.p2p.peerPrivateKey.secretName }}
                  key: {{ $value.p2p.peerPrivateKey.key }}
            - name: TEZOS_ADDRESS
              value: '{{ $value.tezos.address }}'
            - name: TEZOS_PUBLIC_KEY
              value: '{{ $value.tezos.publicKey }}'
            - name: AGGREGATOR_SMART_CONTRACT_ADDRESSES
              value: '{{ join "," $.Values.aggregatorsAddresses }}'
            - name: ALPHAVANTAGE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $value.alphavantage.secretName }}
                  key: {{ $value.alphavantage.key }}
            - name: MESSARI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $value.messari.secretName }}
                  key: {{ $value.messari.key }}
            - name: COINGECKO_SUPPORTED_PLATFORMS
              value: 'ethereum'
            - name: LOG_LEVEL
              value: 'debug'
            - name: USE_FAKE_DATA
              value: 'false'
          image: '{{ $.Values.image.registry }}/{{ $.Values.image.repository }}:{{ $.Values.image.tag }}'
          imagePullPolicy: '{{ $.Values.image.pullPolicy }}'
          ports:
            - name: p2p
              containerPort: 23456
              protocol: TCP
{{ end }}
