---
apiVersion: v1
kind: Service
metadata:
  name: oracle-2
  labels:
    app: oracle-2
spec:
  ports:
    - name: signatory
      port: 6732
      protocol: TCP
      targetPort: signatory
    - name: p2p
      port: 23456
      protocol: TCP
      targetPort: p2p
  selector:
    app: oracle
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oracle-2-config
data:
  secret.json: |
    [
      {
        "name": "12D3KooWBpgAXhUAgjPAwEk5FJ9DRB2kFbuj8KLkPPmqKKmzrXz2",
        "value": "unencrypted:edskRvgMBH37Dci9isEHcdsHQ4ioPdUq3AfXDiAj3ZXiuy3YMs4LEUiZVMaSG9KjTFo78LidgZkdVbkXUamMK2or8UAxB743SH"
      }
    ]
  signatory.yaml: |
    server:
      # Address/Port that Signatory listens on
      address: :6732
      # Address/Port that Signatory serves prometheus metrics on
      utility_address: :9583

    vaults:
      # Name of vault
      # THIS IS NOT RECOMMENDED FOR PRODUCTION, Use local key storage for testing/development only.
      local_file_keys:
        driver: file
        config:
          file: /etc/signatory/secret.json

    # List enabled public keys hashes here
    tezos:
      tz1bfkfgQ8EsH9wrFXueAvm8rKRxzab1vQH1: # Your tezos address
        log_payloads: true
        allowed_operations:
          # List of [generic, block, endorsement]
          - generic
          - block
          - endorsement
          - failing_noop
        allowed_kinds:
          # List of [endorsement, ballot, reveal, transaction, origination, delegation, seed_nonce_revelation, activate_account]
          - transaction
          - endorsement
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-2
  labels:
    app: oracle-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-2
  template:
    metadata:
      labels:
        app: oracle-2
    spec:
      imagePullSecrets:
        - name: 'docker-pull-credentials'
      volumes:
        - name: oracle-2-config
          projected:
            sources:
              - configMap:
                  name: oracle-2-config
      containers:
        - name: oracle
          env:
            - name: RPC_URL
              value: 'https://uoi3x99n7c.ghostnet.tezosrpc.midl.dev'
            - name: SIGNER_URL
              value: 'http://oracle-2.mavryk-oracles.svc.cluster.local:6732'
            - name: P2P_BOOTSTRAP_PEERS
              value: '/ip4/oracle-2.mavryk-oracles.svc.cluster.local/tcp/23456/p2p/12D3KooWJQWBQvefFGj3uAzKGhpZYWYGKtj2fNQAG47aov4uj9p1 /ip4/oracle-2.mavryk-oracles.svc.cluster.local/tcp/23456/p2p/12D3KooWLL2Y1JmrAXkY7r8xbuSRtasfJLAarXmAaZPYxPnzgAJ3'
            - name: P2P_PEER_ID
              value: '12D3KooWBpgAXhUAgjPAwEk5FJ9DRB2kFbuj8KLkPPmqKKmzrXz2'
            - name: P2P_PEER_PUBLIC_KEY
              value: 'CAESIB3LuOsvQXa/QtLkCtHqfEdDnXDiDtGIKB42deJZQSZb'
            - name: P2P_PEER_PRIVATE_KEY
              value: 'CAESQJhgTKhCqif5bg/4RS4mPfjIp/TNA6c7licLcTFumPchHcu46y9Bdr9C0uQK0ep8R0OdcOIO0YgoHjZ14llBJls='
            - name: TEZOS_ADDRESS
              value: 'tz1bfkfgQ8EsH9wrFXueAvm8rKRxzab1vQH1'
            - name: TEZOS_PUBLIC_KEY
              value: 'edpkv758sKsFGRwE3ZNDR1wdVEnxZui344fsxEtCKbpNMcTaQw2Yis'
            - name: TEZOS_SECRET_KEY
              value: 'edskRvgMBH37Dci9isEHcdsHQ4ioPdUq3AfXDiAj3ZXiuy3YMs4LEUiZVMaSG9KjTFo78LidgZkdVbkXUamMK2or8UAxB743SH'
            - name: ALPHAVANTAGE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: ALPHAVANTAGE_API_KEY
            - name: MESSARI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: MESSARI_API_KEY_2
            - name: TEZOS_POLLING_INTERVAL_MILLISECONDS
              value: '2000'
            - name: AGGREGATOR_SMART_CONTRACT_ADDRESSES
              value: 'KT1GFjeSj2iBtqW8S1iSfLNhLkJKTWYSBhAP,KT1CjRdWNttthPGSTtJEj8Se8DtdTjrAR7Wh,KT1N7vwVSiv91QPk1MTgvXLGZ7NuANDEFoXJ,KT1AaSbk1oqkf4HEigVp3KXzsN9Zh41VMvUn'
            - name: LOG_LEVEL
              value: 'verbose'
            - name: USE_FAKE_DATA
              value: 'false'
          image: 'mavrykdynamics/mavryk-oracle:v0.1.1-rc1'
          imagePullPolicy: 'Always'
          ports:
            - name: p2p
              containerPort: 23456
              protocol: TCP
        # - name: signatory
        #   image: 'ecadlabs/signatory:v1.0.0-beta2-amd64'
        #   imagePullPolicy: 'Always'
        #   args:
        #     - -c
        #     - /etc/signatory/signatory.yaml
        #   volumeMounts:
        #     - name: oracle-2-config
        #       mountPath: /etc/signatory
        #   ports:
        #     - name: signatory
        #       containerPort: 6732
        #       protocol: TCP
