apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: signatory
  namespace: mavryk-oracles
spec:
  encryptedData:
    secret.json: AgAJ8XSlWqn/2hbg0n/leuOL+xIEIJd08b8M211WCKwEZ5oL0VeBbT3GGfQ85BLATQOONh4AYvCzndDf4UpTaUI6ODMme0TpFAO5O/8bPXwWxju0WyaRDbngugTJ1xM+KJzeaFV8rgx7/ed4sffGs6H2p+wEoBcVBYkQa7eYdAU4lx/imHYoqXxSX0ZbXNB13P8L9HGgueAmt68hPlw5QECfqw3TqJKzAtplXJgzSbXixWYcpNv2fRl21S4Lx1gxin4EetfrHYsIJhSxh+F7I0wjUHmgV6L7KixBFqvM6whyM8Tv8rBYDHsj40/ncWnP8jnjkshGcFXhF29mDxAlA8TlmtDtKnAG661KxC1vB+pMmNrre4dA3gFZoCgaTzZ8Trj3raz1Ln2bOa0qDtS+BcyKIu6aMsmeHWb8G4/CwDpth2RMOYjO3JrrUoM11lGtXCSbYRvVcPyNHsShAcsdOlh6OyDmrK2xQn2JYfaDSGH0jEoMfbUWnS6jggj8eIpPyFH+k4jUZRM2B31EtfPKLysmRWfQmwfB7i865N2sSRL8Mp8Fp/teBLK24XT7410/kxYsVtfF7oLqsVktNDIvTpKWhSXoumP55x3ZMzA7EXhKw+5U4Gj9oMxRateHWceTTcrSJpwLIdsL1v1xaAZIqdW/oDybsdwX5TUVdy6566oNBRthlKYt1eGKSgS7ZvymLRZI8DzbeAJh35S9zPN7ZNkPdNbBRfv67b54nNgTIhDpLmCShhWjYDq40BDx/hFds/GleHq73dSVMzkuy6lQiZ+dAmJRcrWDYm7A+dXPVabnr/CIgFDxJS2AKuR+Xhjy6tAafFUL0u3oUZ9dsIBxl1LouBHRPRVoeOqJoRvVsv1ooxeirPWkq/tVHSvHamIbQ6aZuKeDLQgRbACqjOpRGljxKh5QoUFWoV+aJ9LI90qGdbkoxoSWVKn7C+7BLpD2kVcr0/TMvC7Ogw8CA5BqoI5sxObgZ8DPLe0fDTGFhjdV7KRQvZmT6sS53QtirTF9EXJsQfJ19sMmqLDMVKgw7UQiWwKrsh77V45Lp4WO7brjOWbLTSukxKvksrNcmNSYyr7DtiCaBGzjYAmgW4qDBcpQWYwMxcP+BTbNrMsdvNPbG6IwesIDGXGloLdq/156VBFyFootirkUrHm60xZVXG1PiMEJ4kaDNVaPsr/iAFzbPhlzEa6FqbCIEynBJfWkukBDMcHtOrROJteEyLe64STmZTZo7qbWNQRQ02yRjUmnIbRqLUkVcPLnSdaspMR65qrmk2YuO3KZmTGvgZSw8iHkGBZYQPlOFAt9w6DGIw0KNtKAA3hQNnoEDeA+XdPUeGm3EAA8eYEbvaHCf5jauGBEGdz0PIA=
  template:
    metadata:
      creationTimestamp: null
      name: signatory
      namespace: mavryk-oracles
    type: Opaque
---
