# generated by datamodel-codegen:
#   filename:  withdrawRewardXtz.json

from __future__ import annotations

from pydantic import BaseModel


class WithdrawRewardXtzParameter(BaseModel):
    __root__: str
