---
apiVersion: v1
kind: Service
metadata:
  name: tzindex
  labels:
    app: tzindex
spec:
  ports:
    - name: api
      port: 8000
      protocol: TCP
      targetPort: api
  selector:
    app: tzindex
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tzindex
  namespace: tzstats
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - api-tzindex.mavryk.io
      secretName: api-tzindex-tls
  rules:
    - host: api-tzindex.mavryk.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tzindex
                port:
                  name: api
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tzindex
  labels:
    app: tzindex
spec:
  podManagementPolicy: Parallel
  replicas: 1
  serviceName: tzindex
  selector:
    matchLabels:
      app: tzindex
  template:
    metadata:
      labels:
        app: tzindex
    spec:
      containers:
        - name: tzindex
          env:
            - name: TZ_RPC_URL
              value: http://tezos-baking-archive-node-rpc.basenet.svc.cluster.local
            - name: TZ_SERVER_HOST
              value: '0.0.0.0'
            - name: TZ_SERVER_ADDR
              value: '0.0.0.0'
            - name: TZ_SERVER_CORS_ENABLE
              value: 'true'
            - name: TZ_SERVER_CORS_ORIGIN
              value: '*'
            - name: TZ_LOG_LEVEL
              value: 'stdout'
            - name: TZ_LIGHT
              value: 'false'
            - name: TZ_FULL
              value: 'true'
          image: mavrykdynamics/tzindex:v15.0.0
          imagePullPolicy: Always
          ports:
            - name: api
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /home/tzindex/db
              name: db-volume
      securityContext:
        fsGroup: 1000
  volumeClaimTemplates:
    - metadata:
        name: db-volume
        namespace: tzstats
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: do-block-storage
        resources:
          requests:
            storage: '10Gi'
