---
apiVersion: v1
kind: Service
metadata:
  name: tzstats
  labels:
    app: tzstats
spec:
  ports:
    - name: frontend
      port: 80
      protocol: TCP
      targetPort: frontend
  selector:
    app: tzstats
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tzstats
  namespace: tzstats
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - '{{ .Values.tzstats.ingress.host }}'
      secretName: '{{ .Values.tzstats.ingress.secretName }}'
  rules:
    - host: '{{ .Values.tzstats.ingress.host }}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tzstats
                port:
                  name: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tzstats
  labels:
    app: tzstats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tzstats
  template:
    metadata:
      labels:
        app: tzstats
    spec:
      containers:
        - name: tzstats
          image: '{{ .Values.tzstats.image.registry }}/{{ .Values.tzstats.image.repository }}:{{ .Values.tzstats.image.tag }}'
          imagePullPolicy: '{{ .Values.tzstats.image.pullPolicy }}'
          ports:
            - name: frontend
              containerPort: 80
              protocol: TCP
