# generated by datamodel-codegen:
#   filename:  togglePauseUntrackFarm.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TogglePauseUntrackFarmParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
