# generated by datamodel-codegen:
#   filename:  togglePauseTrackFarm.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TogglePauseTrackFarmParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
