# generated by datamodel-codegen:
#   filename:  togglePauseCreateFarm.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TogglePauseCreateFarmParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
