# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Any, Dict, Union

from pydantic import BaseModel, Extra


class TokenStandardItem(BaseModel):
    class Config:
        extra = Extra.forbid

    fa12: Dict[str, Any]


class TokenStandardItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    fa2: Dict[str, Any]


class LpToken(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenAddress: str
    tokenId: str
    tokenStandard: Union[TokenStandardItem, TokenStandardItem1]
    tokenBalance: str


class PlannedRewards(BaseModel):
    class Config:
        extra = Extra.forbid

    totalBlocks: str
    currentRewardPerBlock: str
    totalRewards: str


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    blocksPerMinute: str
    forceRewardFromTransfer: bool
    infinite: bool
    lpToken: LpToken
    plannedRewards: PlannedRewards


class BreakGlassConfig(BaseModel):
    class Config:
        extra = Extra.forbid

    depositIsPaused: bool
    withdrawIsPaused: bool
    claimIsPaused: bool


class ClaimedRewards(BaseModel):
    class Config:
        extra = Extra.forbid

    unpaid: str
    paid: str


class Depositors(BaseModel):
    class Config:
        extra = Extra.forbid

    balance: str
    participationRewardsPerShare: str
    unclaimedRewards: str
    claimedRewards: str


class FarmStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    mvkTokenAddress: str
    governanceAddress: str
    metadata: Dict[str, str]
    name: str
    config: Config
    whitelistContracts: Dict[str, str]
    generalContracts: Dict[str, str]
    breakGlassConfig: BreakGlassConfig
    lastBlockUpdate: str
    accumulatedRewardsPerShare: str
    claimedRewards: ClaimedRewards
    depositors: Dict[str, Depositors]
    open: bool
    init: bool
    initBlock: str
    lambdaLedger: Dict[str, str]
