# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Any, Dict, Union

from pydantic import BaseModel, Extra


class BreakGlassConfig(BaseModel):
    class Config:
        extra = Extra.forbid

    claimIsPaused: bool
    depositIsPaused: bool
    withdrawIsPaused: bool


class ClaimedRewards(BaseModel):
    class Config:
        extra = Extra.forbid

    paid: str
    unpaid: str


class Delegators(BaseModel):
    class Config:
        extra = Extra.forbid

    balance: str
    participationMVKPerShare: str
    unclaimedRewards: str


class TokenStandardItem(BaseModel):
    class Config:
        extra = Extra.forbid

    fa12: Dict[str, Any]


class TokenStandardItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    fa2: Dict[str, Any]


class LpToken(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenAddress: str
    tokenBalance: str
    tokenId: str
    tokenStandard: Union[TokenStandardItem, TokenStandardItem1]


class PlannedRewards(BaseModel):
    class Config:
        extra = Extra.forbid

    currentRewardPerBlock: str
    totalBlocks: str
    totalRewards: str


class FarmStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    accumulatedMVKPerShare: str
    admin: str
    blocksPerMinute: str
    breakGlassConfig: BreakGlassConfig
    claimedRewards: ClaimedRewards
    delegators: Dict[str, Delegators]
    forceRewardFromTransfer: bool
    generalContracts: Dict[str, str]
    infinite: bool
    initBlock: str
    lastBlockUpdate: str
    lpToken: LpToken
    open: bool
    plannedRewards: PlannedRewards
    whitelistContracts: Dict[str, str]
