# generated by datamodel-codegen:
#   filename:  dropEmergencyGovernance.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class DropEmergencyGovernanceParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
