# generated by datamodel-codegen:
#   filename:  triggerEmergencyControl.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TriggerEmergencyControlParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    string_0: str
    string_1: str
