# generated by datamodel-codegen:
#   filename:  voteForEmergencyControl.json

from __future__ import annotations

from pydantic import BaseModel


class VoteForEmergencyControlParameter(BaseModel):
    __root__: str
