# generated by datamodel-codegen:
#   filename:  voteForEmergencyControlComplete.json

from __future__ import annotations

from pydantic import BaseModel


class VoteForEmergencyControlCompleteParameter(BaseModel):
    __root__: str
