# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, Extra


class BuyOptions(BaseModel):
    class Config:
        extra = Extra.forbid

    maxAmountPerWalletTotal: str
    whitelistMaxAmountTotal: str
    maxAmountCap: str
    vestingPeriods: str
    tokenXtzPrice: str
    minMvkAmount: str
    totalBought: str


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    vestingPeriodDurationSec: str
    buyOptions: Dict[str, BuyOptions]


class TokenSaleLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenBought: str
    tokenClaimed: str
    claimCounter: str
    lastClaimTimestamp: str
    lastClaimLevel: str


class TokenSaleStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    config: Config
    governanceAddress: str
    metadata: Dict[str, str]
    mvkTokenAddress: str
    tokenSaleEndBlockLevel: str
    tokenSaleEndTimestamp: str
    tokenSaleHasEnded: bool
    tokenSaleHasStarted: bool
    tokenSaleLedger: Dict[str, Dict[str, TokenSaleLedger]]
    tokenSalePaused: bool
    treasuryAddress: str
    whitelistEndTimestamp: str
    whitelistStartTimestamp: str
    whitelistedAddresses: Dict[str, bool]
