import { LENDING_TAB_ID } from './../../../../pages/Dashboard/Dashboard.utils'
import { MainNavigationRoute } from '../../../../utils/TypesAndInterfaces/Navigation'

export const mainNavigationLinks: MainNavigationRoute[] = [
  {
    title: 'Dashboard',
    id: 1,
    path: `dashboard/${LENDING_TAB_ID}`,
    routePath: '/dashboard/:tabId',
    icon: 'menu-compass',
    protectedRoute: false,
    subPages: [
      {
        id: 57483,
        subTitle: 'Overview',
        subPath: `dashboard/${LENDING_TAB_ID}`,
        routeSubPath: '/dashboard/:tabId',
        protectedRoute: false,
      },
      {
        id: 84425,
        subTitle: 'Personal',
        subPath: 'dashboard-personal',
        routeSubPath: '/dashboard-personal',
        protectedRoute: false,
      },
      {
        id: 59526,
        subTitle: 'Vestee Info',
        subPath: 'your-vesting',
        routeSubPath: '/your-vesting',
        protectedRoute: true,
        requires: {
          isVestee: true,
        },
      },
    ],
  },
  {
    title: 'Lend/Borrow',
    id: 7,
    path: 'loans',
    routePath: '/loans',
    icon: 'coin-loan',
    protectedRoute: false,
    subPages: [
      {
        id: 57792,
        subTitle: 'Overview',
        subPath: `loans`,
        routeSubPath: '/loans',
        protectedRoute: false,
      },
      {
        id: 84765,
        subTitle: 'Borrow',
        subPath: 'borrow',
        routeSubPath: '/borrow',
        protectedRoute: false,
      },
      {
        id: 59776,
        subTitle: 'Lend',
        subPath: 'lend',
        routeSubPath: '/lend',
        protectedRoute: false,
      },
      {
        id: 59777,
        subTitle: 'Personal History',
        subPath: 'personal-loans-history',
        routeSubPath: '/personal-loans-history',
        protectedRoute: true,
      },
    ],
  },
  {
    title: 'Vaults',
    id: 8,
    path: 'vaults',
    routePath: '/vaults',
    icon: 'vaults',
    protectedRoute: false,
  },
  {
    title: 'Staking',
    id: 2,
    path: '',
    routePath: '/',
    icon: 'menu-staking',
    protectedRoute: false,
  },
  {
    title: 'Satellites',
    id: 3,
    path: 'satellites',
    routePath: '/satellites',
    icon: 'satellite',
    protectedRoute: false,
    subPages: [
      { id: 57281, subTitle: 'Overview', subPath: 'satellites', routeSubPath: '/satellites', protectedRoute: false },
      {
        id: 57477,
        subTitle: 'Satellite Nodes',
        subPath: 'satellite-nodes',
        routeSubPath: '/satellite-nodes',
        protectedRoute: false,
      },
      {
        id: 55614,
        subTitle: 'Become A Satellite',
        subPath: 'become-satellite',
        routeSubPath: '/become-satellite',
        protectedRoute: false,
      },
      { id: 57471, subTitle: 'Data Feeds', subPath: 'data-feeds', routeSubPath: '/data-feeds', protectedRoute: false },
      { id: 15757, subTitle: 'Users', subPath: 'oracle-users', routeSubPath: '/oracle-users', protectedRoute: false },
    ],
  },
  {
    title: 'Farms',
    id: 5,
    path: 'yield-farms?isLive=1',
    routePath: '/yield-farms',
    icon: 'plant',
    protectedRoute: false,
  },
  {
    title: 'Governance',
    id: 4,
    path: 'governance',
    routePath: '/governance',
    icon: 'hammer',
    protectedRoute: false,
    subPages: [
      { id: 56179, subTitle: 'Proposals', subPath: 'governance', routeSubPath: '/governance', protectedRoute: false },
      {
        id: 31471,
        subTitle: 'Proposal History',
        subPath: 'proposal-history',
        routeSubPath: '/proposal-history',
        protectedRoute: false,
      },
      {
        id: 47294,
        subTitle: 'Satellite Gov.',
        subPath: 'satellite-governance',
        routeSubPath: '/satellite-governance',
        protectedRoute: true,
      },
      {
        id: 79754,
        subTitle: 'Mavryk Council',
        subPath: 'mavryk-council',
        routeSubPath: '/mavryk-council',
        protectedRoute: false,
      },
      {
        id: 38375,
        subTitle: 'Break Glass Actions',
        subPath: 'break-glass-actions',
        routeSubPath: '/break-glass-actions',
        protectedRoute: true,
      },
      {
        id: 561812,
        subTitle: 'Financial Requests',
        subPath: 'financial-requests',
        routeSubPath: '/financial-requests',
        protectedRoute: false,
      },
      {
        id: 59416,
        subTitle: 'Submit Proposal',
        subPath: 'submit-proposal',
        routeSubPath: '/submit-proposal',
        protectedRoute: true,
        requires: {
          isSatellite: true,
        },
      },
      {
        id: 47293,
        subTitle: 'Emergency Gov.',
        subPath: 'emergency-governance',
        routeSubPath: '/emergency-governance',
        protectedRoute: true,
      },

      {
        id: 35587,
        subTitle: 'Contract Status',
        subPath: 'break-glass',
        routeSubPath: '/break-glass',
        protectedRoute: false,
      },
    ],
  },

  {
    title: 'Treasury',
    id: 6,
    path: 'treasury',
    routePath: '/treasury',
    icon: 'treasury',
    protectedRoute: false,
  },
  {
    title: 'Admin',
    id: 9,
    path: 'admin',
    routePath: '/admin',
    icon: 'settings',
    protectedRoute: false,
  },
]
