# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Any, Dict, Optional, Union

from pydantic import BaseModel, Extra, Field


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    financialRequestApprovalPercentage: str
    financialRequestDurationInDays: str


class VoteItem(BaseModel):
    class Config:
        extra = Extra.forbid

    nay: Dict[str, Any]


class VoteItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    pass_: Dict[str, Any] = Field(..., alias='pass')


class VoteItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    yay: Dict[str, Any]


class Voters(BaseModel):
    class Config:
        extra = Extra.forbid

    vote: Union[VoteItem, VoteItem1, VoteItem2]
    totalVotingPower: str
    timeVoted: str


class FinancialRequestLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    requesterAddress: str
    requestType: str
    status: bool
    executed: bool
    treasuryAddress: str
    tokenContractAddress: str
    tokenAmount: str
    tokenName: str
    tokenType: str
    tokenId: str
    requestPurpose: str
    voters: Dict[str, Voters]
    keyHash: Optional[str]
    yayVoteStakedMvkTotal: str
    nayVoteStakedMvkTotal: str
    passVoteStakedMvkTotal: str
    snapshotStakedMvkTotalSupply: str
    stakedMvkPercentageForApproval: str
    stakedMvkRequiredForApproval: str
    requestedDateTime: str
    expiryDateTime: str


class FinancialRequestSnapshotLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    totalStakedMvkBalance: str
    totalDelegatedAmount: str
    totalVotingPower: str


class GovernanceFinancialStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    metadata: Dict[str, str]
    config: Config
    mvkTokenAddress: str
    governanceAddress: str
    whitelistTokenContracts: Dict[str, str]
    whitelistContracts: Dict[str, str]
    generalContracts: Dict[str, str]
    financialRequestLedger: Dict[str, FinancialRequestLedger]
    financialRequestSnapshotLedger: Dict[str, Dict[str, FinancialRequestSnapshotLedger]]
    financialRequestCounter: str
    snapshotStakedMvkTotalSupply: str
    lambdaLedger: Dict[str, str]
