# generated by datamodel-codegen:
#   filename:  tezos_storage.json

from __future__ import annotations

from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Extra, Field


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    financialRequestApprovalPercentage: str
    financialRequestDurationInDays: str


class FinancialRequestLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    requesterAddress: str
    requestType: str
    status: bool
    executed: bool
    treasuryAddress: str
    tokenContractAddress: str
    tokenAmount: str
    tokenName: str
    tokenType: str
    tokenId: str
    requestPurpose: str
    voters: List[str]
    keyHash: Optional[str]
    yayVoteStakedMvkTotal: str
    nayVoteStakedMvkTotal: str
    passVoteStakedMvkTotal: str
    snapshotStakedMvkTotalSupply: str
    stakedMvkPercentageForApproval: str
    stakedMvkRequiredForApproval: str
    requestedDateTime: str
    expiryDateTime: str


class Key(BaseModel):
    class Config:
        extra = Extra.forbid

    nat: str
    address: str


class ValueItem(BaseModel):
    class Config:
        extra = Extra.forbid

    nay: Dict[str, Any]


class ValueItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    pass_: Dict[str, Any] = Field(..., alias='pass')


class ValueItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    yay: Dict[str, Any]


class FinancialRequestVoter(BaseModel):
    class Config:
        extra = Extra.forbid

    key: Key
    value: Union[ValueItem, ValueItem1, ValueItem2]


class GovernanceFinancialStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    metadata: Dict[str, str]
    config: Config
    mvkTokenAddress: str
    governanceAddress: str
    whitelistTokenContracts: Dict[str, str]
    whitelistContracts: Dict[str, str]
    generalContracts: Dict[str, str]
    financialRequestLedger: Dict[str, FinancialRequestLedger]
    financialRequestCounter: str
    financialRequestVoters: List[FinancialRequestVoter]
    lambdaLedger: Dict[str, str]
