apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-gitops
  namespace: '{{ .Release.Namespace }}'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: '{{ .Release.Namespace }}'
    name: in-cluster
  project: default
  source:
    path: src/infrastructure/helm-charts/gitops
    repoURL: git@github.com:mavrykfinance/mavryk-dapp
    targetRevision: staging
    helm:
      valueFiles:
        - network.values.yaml
