name: cert-manager-mavryk
version: 0.0.1
apiVersion: v1
appVersion: v1.10.0
dependencies: # A list of the chart requirements (optional)
  - name: cert-manager
    version: 1.10.0
    repository: https://charts.jetstack.io
