# generated by datamodel-codegen:
#   filename:  propose.json

from __future__ import annotations

from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Extra


class AddOrSetProposalData(BaseModel):
    class Config:
        extra = Extra.forbid

    title: str
    encodedCode: str
    codeDescription: Optional[str]
    index: Optional[str]


class ProposalDatum(BaseModel):
    class Config:
        extra = Extra.forbid

    addOrSetProposalData: AddOrSetProposalData


class ProposalDatum1(BaseModel):
    class Config:
        extra = Extra.forbid

    removeProposalData: str


class TokenItem(BaseModel):
    class Config:
        extra = Extra.forbid

    fa12: str


class Fa2(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenContractAddress: str
    tokenId: str


class TokenItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    fa2: Fa2


class TokenItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    tez: Dict[str, Any]


class TzktTransaction(BaseModel):
    class Config:
        extra = Extra.forbid

    to_: str
    amount: str
    token: Union[TokenItem, TokenItem1, TokenItem2]


class AddOrSetPaymentData(BaseModel):
    class Config:
        extra = Extra.forbid

    title: str
    transaction: TzktTransaction
    index: Optional[str]


class PaymentDatum(BaseModel):
    class Config:
        extra = Extra.forbid

    addOrSetPaymentData: AddOrSetPaymentData


class PaymentDatum1(BaseModel):
    class Config:
        extra = Extra.forbid

    removePaymentData: str


class ProposeParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    title: str
    description: str
    invoice: str
    sourceCode: str
    proposalData: Optional[List[Union[ProposalDatum, ProposalDatum1]]]
    paymentData: Optional[List[Union[PaymentDatum, PaymentDatum1]]]
