# generated by datamodel-codegen:
#   filename:  mintMvkAndTransfer.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class MintMvkAndTransferParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    to_: str
    amt: str
