# generated by datamodel-codegen:
#   filename:  togglePauseStakeMvk.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TogglePauseStakeMvkParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
