# generated by datamodel-codegen:
#   filename:  togglePauseTransfer.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TogglePauseTransferParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
