# generated by datamodel-codegen:
#   filename:  togglePauseEntrypoint.json

from __future__ import annotations

from typing import Any, Dict, Union

from pydantic import BaseModel, Extra


class TargetEntrypointItem(BaseModel):
    class Config:
        extra = Extra.forbid

    mintMvkAndTransfer: bool


class TargetEntrypointItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    stakeTokens: bool


class TargetEntrypointItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    transfer: bool


class TargetEntrypointItem3(BaseModel):
    class Config:
        extra = Extra.forbid

    unstakeTokens: bool


class TargetEntrypointItem4(BaseModel):
    class Config:
        extra = Extra.forbid

    updateTokenOperators: bool


class TogglePauseEntrypointParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    targetEntrypoint: Union[
        TargetEntrypointItem,
        TargetEntrypointItem1,
        TargetEntrypointItem2,
        TargetEntrypointItem3,
        TargetEntrypointItem4,
    ]
    empty: Dict[str, Any]
