# generated by datamodel-codegen:
#   filename:  togglePauseUnstakeMvk.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TogglePauseUnstakeMvkParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
