# generated by datamodel-codegen:
#   filename:  togglePauseMintMvkAndTransfer.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TogglePauseMintMvkAndTransferParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
