# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, Extra


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    requiredFee: str
    stakedMvkPercentageRequired: str
    voteExpiryDays: str


class Voters(BaseModel):
    class Config:
        extra = Extra.forbid

    nat: str
    timestamp: str


class EmergencyGovernanceLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    description: str
    dropped: bool
    executed: bool
    executedDateTime: str
    executedLevel: str
    expirationDateTime: str
    proposerAddress: str
    stakedMvkPercentageRequired: str
    stakedMvkRequiredForTrigger: str
    startDateTime: str
    startLevel: str
    status: bool
    title: str
    totalStakedMvkVotes: str
    voters: Dict[str, Voters]


class EmergencyGovernanceStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    config: Config
    currentEmergencyGovernanceId: str
    emergencyGovernanceLedger: Dict[str, EmergencyGovernanceLedger]
    generalContracts: Dict[str, str]
    nextEmergencyGovernanceProposalId: str
    tempMvkTotalSupply: str
