# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, Extra


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    decimals: str
    minStakedMvkRequiredToTrigger: str
    minStakedMvkRequiredToVote: str
    requiredFee: str
    stakedMvkPercentageRequired: str
    voteExpiryDays: str


class Voters(BaseModel):
    class Config:
        extra = Extra.forbid

    nat: str
    timestamp: str


class EmergencyGovernanceLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    proposerAddress: str
    status: bool
    executed: bool
    dropped: bool
    title: str
    description: str
    voters: Dict[str, Voters]
    totalStakedMvkVotes: str
    stakedMvkPercentageRequired: str
    stakedMvkRequiredForBreakGlass: str
    startDateTime: str
    startLevel: str
    executedDateTime: str
    executedLevel: str
    expirationDateTime: str


class EmergencyGovernanceStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    config: Config
    currentEmergencyGovernanceId: str
    emergencyGovernanceLedger: Dict[str, EmergencyGovernanceLedger]
    generalContracts: Dict[str, str]
    mvkTokenAddress: str
    nextEmergencyGovernanceProposalId: str
    tempStakedMvkTotalSupply: str
