# generated by datamodel-codegen:
#   filename:  tezos_storage.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, Extra


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    decimals: str
    minStakedMvkRequiredToTrigger: str
    minStakedMvkRequiredToVote: str
    proposalDescMaxLength: str
    proposalTitleMaxLength: str
    requiredFeeMutez: str
    stakedMvkPercentageRequired: str
    voteExpiryDays: str


class Voters(BaseModel):
    class Config:
        extra = Extra.forbid

    nat: str
    timestamp: str


class EmergencyGovernanceLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    proposerAddress: str
    executed: bool
    dropped: bool
    title: str
    description: str
    voters: Dict[str, Voters]
    totalStakedMvkVotes: str
    stakedMvkPercentageRequired: str
    stakedMvkRequiredForBreakGlass: str
    startDateTime: str
    startLevel: str
    executedDateTime: str
    executedLevel: str
    expirationDateTime: str


class EmergencyGovernanceStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    metadata: Dict[str, str]
    config: Config
    mvkTokenAddress: str
    governanceAddress: str
    whitelistContracts: Dict[str, str]
    generalContracts: Dict[str, str]
    emergencyGovernanceLedger: Dict[str, EmergencyGovernanceLedger]
    currentEmergencyGovernanceId: str
    nextEmergencyGovernanceId: str
    lambdaLedger: Dict[str, str]
