# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, Extra


class BreakGlassConfig(BaseModel):
    class Config:
        extra = Extra.forbid

    transferIsPaused: bool
    mintMvkAndTransferIsPaused: bool


class TreasuryStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    mvkTokenAddress: str
    governanceAddress: str
    metadata: Dict[str, str]
    breakGlassConfig: BreakGlassConfig
    whitelistContracts: Dict[str, str]
    whitelistTokenContracts: Dict[str, str]
    generalContracts: Dict[str, str]
    lambdaLedger: Dict[str, str]
