# generated by datamodel-codegen:
#   filename:  createFarmMToken.json

from __future__ import annotations

from typing import Any, Dict, Union

from pydantic import BaseModel, Extra


class PlannedRewards(BaseModel):
    class Config:
        extra = Extra.forbid

    totalBlocks: str
    currentRewardPerBlock: str


class TokenStandardItem(BaseModel):
    class Config:
        extra = Extra.forbid

    fa12: Dict[str, Any]


class TokenStandardItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    fa2: Dict[str, Any]


class LpToken(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenAddress: str
    tokenId: str
    tokenStandard: Union[TokenStandardItem, TokenStandardItem1]


class CreateFarmMTokenParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    loanToken: str
    addToGeneralContracts: bool
    forceRewardFromTransfer: bool
    infinite: bool
    plannedRewards: PlannedRewards
    metadata: str
    lpToken: LpToken
