# generated by datamodel-codegen:
#   filename:  addOracle.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class OracleInformation(BaseModel):
    class Config:
        extra = Extra.forbid

    oraclePublicKey: str
    oraclePeerId: str


class AddOracleParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    oracleAddress: str
    oracleInformation: OracleInformation
