# generated by datamodel-codegen:
#   filename:  requestRateUpdateDeviation.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class RequestRateUpdateDeviationParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    roundId: str
    sign: str
