# generated by datamodel-codegen:
#   filename:  requestRateUpdate.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class RequestRateUpdateParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
