# generated by datamodel-codegen:
#   filename:  setObservationReveal.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class PriceSalted(BaseModel):
    class Config:
        extra = Extra.forbid

    nat: str
    string: str
    address: str


class SetObservationRevealParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    roundId: str
    priceSalted: PriceSalted
