# generated by datamodel-codegen:
#   filename:  setObservationCommit.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class SetObservationCommitParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    roundId: str
    sign: str
