# generated by datamodel-codegen:
#   filename:  togglePauseEntrypoint.json

from __future__ import annotations

from typing import Any, Dict, Union

from pydantic import BaseModel, Extra


class TargetEntrypointItem(BaseModel):
    class Config:
        extra = Extra.forbid

    requestRateUpdate: bool


class TargetEntrypointItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    requestRateUpdateDeviation: bool


class TargetEntrypointItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    setObservationCommit: bool


class TargetEntrypointItem3(BaseModel):
    class Config:
        extra = Extra.forbid

    setObservationReveal: bool


class TargetEntrypointItem4(BaseModel):
    class Config:
        extra = Extra.forbid

    withdrawRewardStakedMvk: bool


class TargetEntrypointItem5(BaseModel):
    class Config:
        extra = Extra.forbid

    withdrawRewardXtz: bool


class TogglePauseEntrypointParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    targetEntrypoint: Union[
        TargetEntrypointItem,
        TargetEntrypointItem1,
        TargetEntrypointItem2,
        TargetEntrypointItem3,
        TargetEntrypointItem4,
        TargetEntrypointItem5,
    ]
    empty: Dict[str, Any]
