# generated by datamodel-codegen:
#   filename:  togglePauseRequestRateUpdateDev.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TogglePauseRequestRateUpdateDevParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
