# generated by datamodel-codegen:
#   filename:  togglePauseSetObservationReveal.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TogglePauseSetObservationRevealParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
