# generated by datamodel-codegen:
#   filename:  togglePauseWithdrawRewardSMvk.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TogglePauseWithdrawRewardSMvkParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
