# generated by datamodel-codegen:
#   filename:  togglePauseWithdrawRewardXtz.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TogglePauseWithdrawRewardXtzParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
