# generated by datamodel-codegen:
#   filename:  togglePauseSetObservationCommit.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TogglePauseSetObservationCommitParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
