# generated by datamodel-codegen:
#   filename:  togglePauseRequestRateUpdate.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TogglePauseRequestRateUpdateParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
