# generated by datamodel-codegen:
#   filename:  updateConfig.json

from __future__ import annotations

from typing import Any, Dict, Union

from pydantic import BaseModel, Extra


class UpdateConfigActionItem(BaseModel):
    class Config:
        extra = Extra.forbid

    configDecimals: Dict[str, Any]


class UpdateConfigActionItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    configDevTriggerBanDuration: Dict[str, Any]


class UpdateConfigActionItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    configDeviationRewardAmountXtz: Dict[str, Any]


class UpdateConfigActionItem3(BaseModel):
    class Config:
        extra = Extra.forbid

    configDeviationRewardStakedMvk: Dict[str, Any]


class UpdateConfigActionItem4(BaseModel):
    class Config:
        extra = Extra.forbid

    configNumberBlocksDelay: Dict[str, Any]


class UpdateConfigActionItem5(BaseModel):
    class Config:
        extra = Extra.forbid

    configPerThousandDevTrigger: Dict[str, Any]


class UpdateConfigActionItem6(BaseModel):
    class Config:
        extra = Extra.forbid

    configPercentOracleThreshold: Dict[str, Any]


class UpdateConfigActionItem7(BaseModel):
    class Config:
        extra = Extra.forbid

    configRequestRateDevDepositFee: Dict[str, Any]


class UpdateConfigActionItem8(BaseModel):
    class Config:
        extra = Extra.forbid

    configRewardAmountStakedMvk: Dict[str, Any]


class UpdateConfigActionItem9(BaseModel):
    class Config:
        extra = Extra.forbid

    configRewardAmountXtz: Dict[str, Any]


class UpdateConfigParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    updateConfigNewValue: str
    updateConfigAction: Union[
        UpdateConfigActionItem,
        UpdateConfigActionItem1,
        UpdateConfigActionItem2,
        UpdateConfigActionItem3,
        UpdateConfigActionItem4,
        UpdateConfigActionItem5,
        UpdateConfigActionItem6,
        UpdateConfigActionItem7,
        UpdateConfigActionItem8,
        UpdateConfigActionItem9,
    ]
