# generated by datamodel-codegen:
#   filename:  withdrawRewardStakedMvk.json

from __future__ import annotations

from pydantic import BaseModel


class WithdrawRewardStakedMvkParameter(BaseModel):
    __root__: str
