# generated by datamodel-codegen:
#   filename:  getTotalAndMaximumSupply.json

from __future__ import annotations

from pydantic import BaseModel


class GetTotalAndMaximumSupplyParameter(BaseModel):
    __root__: str
