# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, Extra


class GovernanceProxyStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    generalContracts: Dict[str, str]
    governanceAddress: str
    lambdaLedger: Dict[str, str]
    metadata: Dict[str, str]
    mvkTokenAddress: str
    proxyLambdaLedger: Dict[str, str]
    whitelistContracts: Dict[str, str]
    whitelistTokenContracts: Dict[str, str]
