# generated by datamodel-codegen:
#   filename:  tezos_storage.json

from __future__ import annotations

from typing import Any, Dict, List, Union

from pydantic import BaseModel, Extra


class Depositor(BaseModel):
    class Config:
        extra = Extra.forbid

    any: Dict[str, Any]


class Depositor1(BaseModel):
    class Config:
        extra = Extra.forbid

    whitelist: List[str]


class Handle(BaseModel):
    class Config:
        extra = Extra.forbid

    id: str
    owner: str


class VaultStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    depositors: Union[Depositor, Depositor1]
    handle: Handle
    name: str
