{{if .Values.argoCD }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.spec.environment }}-argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    name: {{ .Values.spec.clusterName }}
  project: default
  source:
    path: src/infrastructure/helm-charts/argo-cd
    repoURL: git@github.com:mavrykfinance/mavryk-dapp
    targetRevision: staging
    helm:
      valueFiles:
        - {{ .Values.argoCD.valueFiles }}
{{end}}