{{if .Values.basenet }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.spec.environment }}-better-call-dev
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: better-call-dev
    name: {{ .Values.spec.clusterName }}
  project: default
  source:
    path: src/infrastructure/helm-charts/better-call-dev
    repoURL: git@github.com:mavrykfinance/mavryk-dapp
    targetRevision: staging
    helm:
      valueFiles:
        - {{ .Values.betterCallDev.valueFiles }}
{{end}}