# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict, List

from pydantic import BaseModel, Extra


class ActionsLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    actionType: str
    addressMap: Dict[str, str]
    executed: bool
    executedDateTime: str
    executedLevel: str
    expirationDateTime: str
    initiator: str
    natMap: Dict[str, str]
    signers: List[str]
    signersCount: str
    startDateTime: str
    startLevel: str
    status: str


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    actionExpiryDays: str
    threshold: str


class BreakGlassStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    actionCounter: str
    actionsLedger: Dict[str, ActionsLedger]
    admin: str
    config: Config
    councilMembers: List[str]
    developerAddress: str
    generalContracts: Dict[str, str]
    glassBroken: bool
    whitelistContracts: Dict[str, str]
