# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict, List

from pydantic import BaseModel, Extra


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    threshold: str
    actionExpiryDays: str
    councilMemberNameMaxLength: str
    councilMemberWebsiteMaxLength: str
    councilMemberImageMaxLength: str


class CouncilMembers(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    website: str
    image: str


class ActionsLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    actionType: str
    dataMap: Dict[str, str]
    executed: bool
    executedDateTime: str
    executedLevel: str
    expirationDateTime: str
    initiator: str
    signers: List[str]
    signersCount: str
    startDateTime: str
    startLevel: str
    status: str


class BreakGlassStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    metadata: Dict[str, str]
    config: Config
    mvkTokenAddress: str
    governanceAddress: str
    whitelistContracts: Dict[str, str]
    generalContracts: Dict[str, str]
    glassBroken: bool
    councilMembers: Dict[str, CouncilMembers]
    actionsLedger: Dict[str, ActionsLedger]
    actionCounter: str
    lambdaLedger: Dict[str, str]
