apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: s3-credentials
  namespace: loki
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgADCi8dn5cviyv6B4cut7nnpAmvAIwjgd5a7D2e//v8T13j70KBsm6MnvWtMp3jw0kUoerA1MgSELKXBUDaExtI4H9KMnHNQuPxuMsslygnQLtuvG8qk1cBfhzW3intFoOl0uSoY26tDk1OFQniSjwhwjIHxO7wt5Rzx07ZNntdnKptDLKF0mW80cFLN28wJrIEjyqX3mXRXRt9wW3Wmkr10gj23k6nMsJmMIOwaYFdEOTBfG55mqnySnmSzUUopBgh0MqQsvBYZhD0/Wk7NlXGFDdfWTE8/wRlexpypy94ACQ8AaHb8kwAciLeaNFE5l9/kWcR16wYiDYjWJ8Pmh3yV6pUcKpHJ3s1r8RuagkYWGg90Y/Gq+UUm86io2UETGETWmWf+vvc6nAs2uL2zPSjeSg0fKCdXOQ6Y335rm+rd9xMzRxOEwiCn4xCcY15gWy30NhvHmRLDgpXv6EaF09aHdYdbtOIaj8QTFWHEhFy7+zHoe/3WHvMnkdh03pdiVs5BTwi8w8+BTtk8E03wSqHXpLt9IRiWhwUhO33zHhptmkdhVep7R5w5IcVgdnV1f6uJEKEEK2aooq9iCFFMEUYDnZcMQwMn4MGMKoZopqESN6rYxuYE4oi0DIjFluDqZT0ziUARGQnxTetBb6hvwrumBXDtGZk+ulrW7OEkt6D2SRLOIlJdoyfkrP22zPpkUYg6/KjGfurz29jvb+619xBTLr53w==
    AWS_SECRET_ACCESS_KEY: AgCJJvDB3IDFDqcWyHkqYSXeQyKDs/u2eCdItwvddT2H185c7YDgF7JCC9YPrunDAGzcN/DPJRVc9JoO0R3uIHy4i3gM6T6e9yH+7myIFBe2D6dX4vOSvxZmmXZCAuFZwLHUHlhHhz51tbydBlOoG4Fj8xYPdOJguoXLalyKmO2+RCJztSg5t0jamyP1vGuoyzR7uyW9LmfPdGI54Zc/SLvyYkoiCAWjQ3gfCH+eXd8UkS2kn/+9rRpR2rJo1m3yAxMQBzReJFtvai3A5V9SL2GpDlFrtXNGpB+A0J1R761E9e+RQQd8Yo68gBc6brPeCuVmvjiGJl+76wGsQh8//962idrAI6516gGQ7hL2j8lxxeYUFqrj60STxBk8BBuKplQN9HeRqLIVX6NI0ku0y9GLGMXAMNnfKWVKMDIgwH7K8JRBWCvolf2DjKG8mMlANhhtvOrnipwaKU68L8bq7l6kaOru58YZKpnuj55y1P58f0Mur129ASwrmzMpGzvK8GMazQBLGiU06XfMln02DdNeSj5zhvl3sQRGAjCTSqu0BK70UsSXpyTvkj5nu6ySjQmItknaq1MFAVy2+IR+lFCA2tPftYDhwys7Yp1T4ZmmgvFEHR4WAb9uMR5+8UA4seVLy/EtPv0YhkcPgE19hJymxS0ih2cXqKcyURvCzr+BlsAAF0a0CXIJt0cCU3Yhd52Do/F1L47wHpPSZei+jh0SAVYhIl10x11PFi/7/OZj4hWiBfpeZEk7
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: s3-credentials
      namespace: loki
    type: Opaque

