# generated by datamodel-codegen:
#   filename:  updateWhitelistContracts.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class UpdateWhitelistContractsParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    whitelistContractName: str
    whitelistContractAddress: str
