# generated by datamodel-codegen:
#   filename:  initFarm.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class FarmConfig(BaseModel):
    class Config:
        extra = Extra.forbid

    totalBlocks: str
    currentRewardPerBlock: str
    forceRewardFromTransfer: bool
    infinite: bool


class InitFarmParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    targetFarmAddress: str
    farmConfig: FarmConfig
