# generated by datamodel-codegen:
#   filename:  setProxyLambda.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class SetProxyLambdaParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    id: str
    func_bytes: str
