apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare
  namespace: external-dns
spec:
  encryptedData:
    CF_API_TOKEN: AgBqr3nIhlBSccrtsV+YeNClCINf8c3+ZyWmg+z9wvnPu1/DAqUlJes215CBuqX4LMCQZjBwvElICiHgTcLgYGyb1Iy+CtP/Hk7g/6/K8FZzms34yVZMmgeaBdBA7BHpbEhVp7IxWlAyYVbIuEZQqxhw/0iyhgMJYkcy5wydK+LPwEs5lM7tVOH13M9s6rnn/PvRUfISqUHhFXKVT5oF3gicLMuzY5S9T+L4CJDa5IsTlku+lpVLRbGaHjUaxn3iUvzMCLDw8qCbc/Qcs4+gitpl7RGf56oq+/RMSjDLM7EYYUB+vTTV+ZodW5pRHlpQnfryIPrBtxbesiALqOdaRQzraQoOBMHXshgmOh51QtSoyw13g4kmY/x/Ex/GfW8+bMZyY3QhEP2ypXex/BW4oeqBtJ1h5u2DwDc+YrzmuKAS6qf4IIFgdHbDafyfwcH53u9AOKLoCR5t7y9ih8sd7LtYmscylqEtttvk0ybSVEHo8FGlnSamTdyQnzHQY+ymzFxLvPEb9N8NXEE/iDaxSCL3pbPWg+Edn0l9xdioKrpQeTq/YOFXFCrTdG21P7Yq7OhPfb1Rkk9CH7JVLifUrO80H+6bmmNdD4Muf9K0cNwDI7EZ12mOdE0nrFQRq3OkKmKfT3svXIspwMTunJyav21KHbtoHd2AnNL1cltKZ1i71ITd8agD/7/fnegex40oih4=
    cloudflare_api_token: AgCEr0GtKe+u9/PPIcrbwGWhDclBInQWAnlCxEL8BLYeG7BZc4pNks84ZKvlmZMHg0R0mEyIp9PmewIpWAWgCORAySZf4unsLcU4rfdJgvKB0JOwNSEhfljJnSxJA2Nubp9PDtspbnN2vX7NED+I+IoREhD1Gzluho/wt2s1KYvpWlgDTIy8TC6V8xsSqNRTNjyDtQA74WUYAYVwxywvmapujLXWd+KhLHr4FbP8+P++zwx/czWIh/gBHn0z0IZb0hGhUNGW+qQ3VQPdVc67RSoYcfWNlJ6nh4SOV7P/aipsitp/bbZ7ijzMn4NV2job0iDprkoyM9oNKUnEqpiTMdjrvSQUkI/aA0KV8rlHrrAkwXL9CXa/eKaYcYwKxgDsiqurDR5Q82fk2ZuFtrrcNQhal63HAhbwjoE+1pzonRUEci2peTn1SQmNVSQ9Pm/RdeS9aSd1TDpXnYDAyLeYwDCBWfEcwzgX/i8hVSQGSzWJA2r/r0vKB+m6SZHctIqviPJKshPzMvMK+ASN5pLniflx1e1bfSpQoTtzNmMvNeGvBM4ZX7NMxKY9EqSpw1g2IAcTsEJFRp+KAMwNfZxxqOkUGheNuw6GXQdF70QnkHelHMnO0c4rnR9RkuP7lB2QxWK6y7iZrynA2/0lyLQXPRJz1I7+W719lYCy2zgbchXcGGUlHt5f+/myNQd6GVxkhnonUlp+iH10dlk/pwSZE//d+swsKcdiBBM6G6KKOR7T8Bo7xGPHvSuI
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare
      namespace: external-dns
    type: Opaque

