# generated by DipDup 8.2.2

from __future__ import annotations

from typing import List

from pydantic import RootModel


class RemoveBreakGlassControlParameter(RootModel[List[str]]):
    root: List[str]
