# generated by datamodel-codegen:
#   filename:  updateConfig.json

from __future__ import annotations

from typing import Any, Dict, Union

from pydantic import BaseModel, Extra


class UpdateConfigActionItem(BaseModel):
    class Config:
        extra = Extra.forbid

    configActionExpiryDays: Dict[str, Any]


class UpdateConfigActionItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    configCouncilImageMaxLength: Dict[str, Any]


class UpdateConfigActionItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    configCouncilNameMaxLength: Dict[str, Any]


class UpdateConfigActionItem3(BaseModel):
    class Config:
        extra = Extra.forbid

    configCouncilWebsiteMaxLength: Dict[str, Any]


class UpdateConfigActionItem4(BaseModel):
    class Config:
        extra = Extra.forbid

    configThreshold: Dict[str, Any]


class UpdateConfigParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    updateConfigNewValue: str
    updateConfigAction: Union[
        UpdateConfigActionItem,
        UpdateConfigActionItem1,
        UpdateConfigActionItem2,
        UpdateConfigActionItem3,
        UpdateConfigActionItem4,
    ]
