# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, Extra


class BreakGlassConfig(BaseModel):
    class Config:
        extra = Extra.forbid

    delegateToSatelliteIsPaused: bool
    registerAsSatelliteIsPaused: bool
    undelegateFromSatelliteIsPaused: bool
    unregisterAsSatelliteIsPaused: bool
    updateSatelliteRecordIsPaused: bool


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    delegationRatio: str
    maxSatellites: str
    minimumStakedMvkBalance: str


class DelegateLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    delegatedDateTime: str
    satelliteAddress: str


class SatelliteLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    description: str
    image: str
    name: str
    registeredDateTime: str
    satelliteFee: str
    stakedMvkBalance: str
    status: str
    totalDelegatedAmount: str


class DelegationStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    breakGlassConfig: BreakGlassConfig
    config: Config
    delegateLedger: Dict[str, DelegateLedger]
    generalContracts: Dict[str, str]
    satelliteLedger: Dict[str, SatelliteLedger]
    whitelistContracts: Dict[str, str]
