# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Extra, Field


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    successReward: str
    cycleVotersReward: str
    minProposalRoundVotePercentage: str
    minProposalRoundVotesRequired: str
    minQuorumPercentage: str
    minYayVotePercentage: str
    votingPowerRatio: str
    proposalSubmissionFeeMutez: str
    maxProposalsPerSatellite: str
    blocksPerMinute: str
    blocksPerProposalRound: str
    blocksPerVotingRound: str
    blocksPerTimelockRound: str
    proposalMetadataTitleMaxLength: str
    proposalTitleMaxLength: str
    proposalDescriptionMaxLength: str
    proposalInvoiceMaxLength: str
    proposalSourceCodeMaxLength: str


class ProposalMetadatum(BaseModel):
    class Config:
        extra = Extra.forbid

    title: str
    data: str


class TokenItem(BaseModel):
    class Config:
        extra = Extra.forbid

    fa12: str


class Fa2(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenContractAddress: str
    tokenId: str


class TokenItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    fa2: Fa2


class TokenItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    tez: Dict[str, Any]


class Transaction(BaseModel):
    class Config:
        extra = Extra.forbid

    to_: str
    amount: str
    token: Union[TokenItem, TokenItem1, TokenItem2]


class PaymentMetadatum(BaseModel):
    class Config:
        extra = Extra.forbid

    title: str
    transaction: Transaction


class ProposalVotersMap(BaseModel):
    class Config:
        extra = Extra.forbid

    nat: str
    timestamp: str


class OrItem(BaseModel):
    class Config:
        extra = Extra.forbid

    nay: Dict[str, Any]


class OrItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    pass_: Dict[str, Any] = Field(..., alias='pass')


class OrItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    yay: Dict[str, Any]


class Voters(BaseModel):
    class Config:
        extra = Extra.forbid

    nat: str
    timestamp: str
    or_: Union[OrItem, OrItem1, OrItem2] = Field(..., alias='or')


class ProposalLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    proposerAddress: str
    proposalMetadata: Dict[str, Optional[ProposalMetadatum]]
    proposalMetadataExecutionCounter: str
    paymentMetadata: Dict[str, Optional[PaymentMetadatum]]
    status: str
    title: str
    description: str
    invoice: str
    sourceCode: str
    successReward: str
    executed: bool
    paymentProcessed: bool
    locked: bool
    proposalVoteCount: str
    proposalVoteStakedMvkTotal: str
    proposalVotersMap: Dict[str, ProposalVotersMap]
    minProposalRoundVotePercentage: str
    minProposalRoundVotesRequired: str
    yayVoteCount: str
    yayVoteStakedMvkTotal: str
    nayVoteCount: str
    nayVoteStakedMvkTotal: str
    passVoteCount: str
    passVoteStakedMvkTotal: str
    voters: Dict[str, Voters]
    minQuorumPercentage: str
    minQuorumStakedMvkTotal: str
    minYayVotePercentage: str
    quorumCount: str
    quorumStakedMvkTotal: str
    startDateTime: str
    cycle: str
    currentCycleStartLevel: str
    currentCycleEndLevel: str


class SnapshotLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    totalStakedMvkBalance: str
    totalDelegatedAmount: str
    totalVotingPower: str
    cycle: str


class RoundItem(BaseModel):
    class Config:
        extra = Extra.forbid

    proposal: Dict[str, Any]


class RoundItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    timelock: Dict[str, Any]


class RoundItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    voting: Dict[str, Any]


class CurrentCycleInfo(BaseModel):
    class Config:
        extra = Extra.forbid

    round: Union[RoundItem, RoundItem1, RoundItem2]
    blocksPerProposalRound: str
    blocksPerVotingRound: str
    blocksPerTimelockRound: str
    roundStartLevel: str
    roundEndLevel: str
    cycleEndLevel: str
    roundProposals: Dict[str, str]
    roundProposers: Dict[str, List[str]]
    roundVotes: Dict[str, str]
    cycleTotalVotersReward: str
    minQuorumStakedMvkTotal: str


class GovernanceStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    metadata: Dict[str, str]
    config: Config
    mvkTokenAddress: str
    governanceProxyAddress: str
    whitelistContracts: Dict[str, str]
    generalContracts: Dict[str, str]
    whitelistDevelopers: List[str]
    proposalLedger: Dict[str, ProposalLedger]
    snapshotLedger: Dict[str, SnapshotLedger]
    currentCycleInfo: CurrentCycleInfo
    nextProposalId: str
    cycleCounter: str
    cycleHighestVotedProposalId: str
    timelockProposalId: str
    lambdaLedger: Dict[str, str]
