# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Any, Dict, Union

from pydantic import BaseModel, Extra


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    successReward: str
    minProposalRoundVotePercentage: str
    minProposalRoundVotesRequired: str
    minQuorumPercentage: str
    minQuorumMvkTotal: str
    votingPowerRatio: str
    proposalSubmissionFee: str
    minimumStakeReqPercentage: str
    maxProposalsPerDelegate: str
    newBlockTimeLevel: str
    newBlocksPerMinute: str
    blocksPerMinute: str
    blocksPerProposalRound: str
    blocksPerVotingRound: str
    blocksPerTimelockRound: str
    financialRequestApprovalPercentage: str
    financialRequestDurationInDays: str


class VoteItem(BaseModel):
    class Config:
        extra = Extra.forbid

    approve: Dict[str, Any]


class VoteItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    disapprove: Dict[str, Any]


class Voters(BaseModel):
    class Config:
        extra = Extra.forbid

    vote: Union[VoteItem, VoteItem1]
    totalVotingPower: str
    timeVoted: str


class FinancialRequestLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    requesterAddress: str
    requestType: str
    status: bool
    ready: bool
    executed: bool
    treasuryAddress: str
    tokenContractAddress: str
    tokenAmount: str
    tokenName: str
    tokenType: str
    tokenId: str
    requestPurpose: str
    voters: Dict[str, Voters]
    approveVoteTotal: str
    disapproveVoteTotal: str
    snapshotStakedMvkTotalSupply: str
    stakedMvkPercentageForApproval: str
    stakedMvkRequiredForApproval: str
    requestedDateTime: str
    expiryDateTime: str


class FinancialRequestSnapshotLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    totalMvkBalance: str
    totalDelegatedAmount: str
    totalVotingPower: str


class PassVotersMap(BaseModel):
    class Config:
        extra = Extra.forbid

    nat: str
    timestamp: str


class Voters1(BaseModel):
    class Config:
        extra = Extra.forbid

    nat_0: str
    nat_1: str
    timestamp: str


class ProposalLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    proposerAddress: str
    proposalMetadata: Dict[str, str]
    status: str
    title: str
    description: str
    invoice: str
    sourceCode: str
    successReward: str
    executed: bool
    locked: bool
    passVoteCount: str
    passVoteMvkTotal: str
    passVotersMap: Dict[str, PassVotersMap]
    minProposalRoundVotePercentage: str
    minProposalRoundVotesRequired: str
    upvoteCount: str
    upvoteMvkTotal: str
    downvoteCount: str
    downvoteMvkTotal: str
    abstainCount: str
    abstainMvkTotal: str
    voters: Dict[str, Voters1]
    minQuorumPercentage: str
    minQuorumMvkTotal: str
    quorumCount: str
    quorumMvkTotal: str
    startDateTime: str
    cycle: str
    currentCycleStartLevel: str
    currentCycleEndLevel: str


class SnapshotLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    totalMvkBalance: str
    totalDelegatedAmount: str
    totalVotingPower: str
    currentCycleStartLevel: str
    currentCycleEndLevel: str


class GovernanceStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    activeSatellitesMap: Dict[str, str]
    admin: str
    config: Config
    currentCycleEndLevel: str
    currentRound: str
    currentRoundEndLevel: str
    currentRoundHighestVotedProposalId: str
    currentRoundProposals: Dict[str, str]
    currentRoundStartLevel: str
    currentRoundVotes: Dict[str, str]
    cycleCounter: str
    financialRequestCounter: str
    financialRequestLedger: Dict[str, FinancialRequestLedger]
    financialRequestSnapshotLedger: Dict[str, Dict[str, FinancialRequestSnapshotLedger]]
    generalContracts: Dict[str, str]
    governanceLambdaLedger: Dict[str, str]
    mvkTokenAddress: str
    nextProposalId: str
    proposalLedger: Dict[str, ProposalLedger]
    snapshotLedger: Dict[str, SnapshotLedger]
    snapshotMvkTotalSupply: str
    snapshotStakedMvkTotalSupply: str
    startLevel: str
    tempFlag: str
    timelockProposalId: str
    whitelistContracts: Dict[str, str]
    whitelistTokenContracts: Dict[str, str]
