---
apiVersion: v1
kind: Service
metadata:
  name: medium
spec:
  ports:
    - name: http
      port: 3002
      protocol: TCP
      targetPort: http
  selector:
    app: medium
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medium
  labels:
    app: medium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medium
  template:
    metadata:
      labels:
        app: medium
    spec:
      containers:
        - name: medium
          image: shperung/node-mavryk:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
              name: http
              protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: medium
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-expose-headers: '*'
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/cors-allow-methods: PUT, GET, POST, OPTIONS, DELETE, PATCH
spec:
  tls:
    - hosts:
        - medium-api.mavryk.finance
      secretName: medium-api-mavryk-tls
  rules:
    - host: medium-api.mavryk.finance
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: medium
                port:
                  number: 3002
