# generated by datamodel-codegen:
#   filename:  updateWhitelistTokenContracts.json

from __future__ import annotations

<<<<<<< HEAD
from typing import Any, Dict, Union

from pydantic import BaseModel, Extra


class UpdateTypeItem(BaseModel):
    class Config:
        extra = Extra.forbid

    remove: Dict[str, Any]


class UpdateTypeItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    update: Dict[str, Any]


=======
from pydantic import BaseModel, Extra


>>>>>>> 63661dace (handlers refactored for dipdup 7)
class UpdateWhitelistTokenContractsParameter(BaseModel):
    class Config:
        extra = Extra.forbid

<<<<<<< HEAD
    tokenContractAddress: str
    updateType: Union[UpdateTypeItem, UpdateTypeItem1]
=======
    tokenContractName: str
    tokenContractAddress: str
>>>>>>> 63661dace (handlers refactored for dipdup 7)
