# generated by datamodel-codegen:
#   filename:  councilActionChangeMember.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class CouncilActionChangeMemberParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    address_0: str
    address_1: str
