# generated by datamodel-codegen:
#   filename:  councilActionAddMember.json

from __future__ import annotations

from pydantic import BaseModel


class CouncilActionAddMemberParameter(BaseModel):
    __root__: str
