# generated by datamodel-codegen:
#   filename:  councilActionUpdateBlocksPerMin.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class CouncilActionUpdateBlocksPerMinParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    contractAddress: str
    newBlocksPerMinute: str
