# generated by datamodel-codegen:
#   filename:  councilActionUpdateBlocksPerMin.json

from __future__ import annotations

from pydantic import BaseModel


class CouncilActionUpdateBlocksPerMinParameter(BaseModel):
    __root__: str
