# generated by datamodel-codegen:
#   filename:  createTreasury.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class CreateTreasuryParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    addToGeneralContracts: bool
    metadata: str
