# generated by datamodel-codegen:
#   filename:  createTreasury.json

from __future__ import annotations

from typing import Dict, Union

from pydantic import BaseModel, Extra


class CreateTreasuryParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    addToGeneralContracts: bool
    metadata: Union[int, Dict[str, str]]
