# generated by datamodel-codegen:
#   filename:  togglePauseCreateTreasury.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TogglePauseCreateTreasuryParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
