# generated by datamodel-codegen:
#   filename:  togglePauseUntrackTreasury.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TogglePauseUntrackTreasuryParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
