# generated by datamodel-codegen:
#   filename:  togglePauseTrackTreasury.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TogglePauseTrackTreasuryParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
