# generated by datamodel-codegen:
#   filename:  updateWhitelistTokenContracts.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class UpdateWhitelistTokenContractsParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenContractName: str
    tokenContractAddress: str
