# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict, List

from pydantic import BaseModel, Extra


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    actionExpiryDays: str
    threshold: str


class CouncilActionsLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    actionType: str
    address_param_1: str
    address_param_2: str
    address_param_3: str
    executed: bool
    executedDateTime: str
    executedLevel: str
    expirationDateTime: str
    initiator: str
    nat_param_1: str
    nat_param_2: str
    nat_param_3: str
    signers: List[str]
    signersCount: str
    startDateTime: str
    startLevel: str
    status: str
    string_param_1: str
    string_param_2: str
    string_param_3: str


class CouncilStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    actionCounter: str
    admin: str
    config: Config
    councilActionsLedger: Dict[str, CouncilActionsLedger]
    councilMembers: List[str]
    generalContracts: Dict[str, str]
    tempString: str
    thresholdSigners: str
    whitelistContracts: Dict[str, str]
