# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict, List

from pydantic import BaseModel, Extra


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    actionExpiryDays: str
    threshold: str


class CouncilActionsLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    actionType: str
    addressMap: Dict[str, str]
    executed: bool
    executedDateTime: str
    executedLevel: str
    expirationDateTime: str
    initiator: str
    natMap: Dict[str, str]
    signers: List[str]
    signersCount: str
    startDateTime: str
    startLevel: str
    status: str
    stringMap: Dict[str, str]


class CouncilStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    actionCounter: str
    admin: str
    config: Config
    councilActionsLedger: Dict[str, CouncilActionsLedger]
    councilMembers: List[str]
    generalContracts: Dict[str, str]
    mvkTokenAddress: str
    whitelistContracts: Dict[str, str]
