# generated by datamodel-codegen:
#   filename:  tezos_storage.json

from __future__ import annotations

from typing import Dict, List

from pydantic import BaseModel, Extra


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    threshold: str
    actionExpiryDays: str
    councilMemberNameMaxLength: str
    councilMemberWebsiteMaxLength: str
    councilMemberImageMaxLength: str
    requestTokenNameMaxLength: str
    requestPurposeMaxLength: str


class CouncilMembers(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    website: str
    image: str


class CouncilActionsLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    initiator: str
    actionType: str
    signers: List[str]
    executed: bool
    status: str
    signersCount: str
    dataMap: Dict[str, str]
    startDateTime: str
    startLevel: str
    executedDateTime: str
    executedLevel: str
    expirationDateTime: str


class CouncilStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    metadata: Dict[str, str]
    config: Config
    mvkTokenAddress: str
    governanceAddress: str
    whitelistContracts: Dict[str, str]
    generalContracts: Dict[str, str]
    councilMembers: Dict[str, CouncilMembers]
    councilActionsLedger: Dict[str, CouncilActionsLedger]
    actionCounter: str
    lambdaLedger: Dict[str, str]
