# generated by datamodel-codegen:
#   filename:  councilActionSetBaker.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class CouncilActionSetBakerParameter(BaseModel):
    __root__: Optional[str]
