# generated by datamodel-codegen:
#   filename:  registerAggregator.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class AggregatorPair(BaseModel):
    class Config:
        extra = Extra.forbid

    string_0: str
    string_1: str


class RegisterAggregatorParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    aggregatorPair: AggregatorPair
    aggregatorAddress: str
