# generated by datamodel-codegen:
#   filename:  unbanSatellite.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class UnbanSatelliteParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    satelliteToBeUnbanned: str
    purpose: str
