# generated by datamodel-codegen:
#   filename:  unsuspendSatellite.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class UnsuspendSatelliteParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    satelliteToBeUnsuspended: str
    purpose: str
