# generated by datamodel-codegen:
#   filename:  updateAggregatorStatus.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class UpdateAggregatorStatusParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    aggregatorAddress: str
    status: str
    purpose: str
