# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, Extra


class ClaimLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    amountClaimed: str
    blockLevelClaimed: str
    dateTimeClaimed: str
    remainderVested: str


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    blocksPerMinute: str
    blocksPerMonth: str
    defaultCliffPeriod: str
    defaultCooldownPeriod: str
    newBlockTimeLevel: str
    newBlocksPerMinute: str


class VesteeLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    claimAmountPerMonth: str
    cliffMonths: str
    endCliffBlock: str
    endCliffDateTime: str
    endVestingBlock: str
    endVestingDateTime: str
    lastClaimedBlock: str
    lastClaimedTimestamp: str
    monthsClaimed: str
    monthsRemaining: str
    nextRedemptionBlock: str
    nextRedemptionTimestamp: str
    startBlock: str
    startTimestamp: str
    status: str
    totalAllocatedAmount: str
    totalClaimed: str
    totalRemainder: str
    vestingMonths: str


class VestingStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    claimLedger: Dict[str, ClaimLedger]
    config: Config
    generalContracts: Dict[str, str]
    mvkTokenAddress: str
    tempBlockLevel: str
    totalVestedAmount: str
    vesteeLedger: Dict[str, VesteeLedger]
    whitelistContracts: Dict[str, str]
