# generated by datamodel-codegen:
#   filename:  increaseRewardPerBlock.json

from __future__ import annotations

from pydantic import BaseModel


class IncreaseRewardPerBlockParameter(BaseModel):
    __root__: str
