# generated by datamodel-codegen:
#   filename:  togglePauseWithdraw.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TogglePauseWithdrawParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
