# generated by datamodel-codegen:
#   filename:  togglePauseClaim.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TogglePauseClaimParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
