# generated by datamodel-codegen:
#   filename:  toggleForceRewardFromTransfer.json

from __future__ import annotations

from pydantic import BaseModel


class ToggleForceRewardFromTransferParameter(BaseModel):
    __root__: bool
