# generated by datamodel-codegen:
#   filename:  togglePauseDeposit.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TogglePauseDepositParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
