# generated by datamodel-codegen:
#   filename:  updateBlocksPerMinute.json

from __future__ import annotations

from pydantic import BaseModel


class UpdateBlocksPerMinuteParameter(BaseModel):
    __root__: str
