# generated by datamodel-codegen:
#   filename:  updateSatelliteRecord.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Extra


class UpdateSatelliteRecordParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    description: str
    image: str
    website: str
    satelliteFee: str
    oraclePublicKey: Optional[str]
    oraclePeerId: Optional[str]
