# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, Extra


class BreakGlassConfig(BaseModel):
    class Config:
        extra = Extra.forbid

    updateRewardsIsPaused: bool
    claimRewardsIsPaused: bool
    empty: Dict[str, Any]


class Key(BaseModel):
    class Config:
        extra = Extra.forbid

    address: str
    string: str


class Value(BaseModel):
    class Config:
        extra = Extra.forbid

    unpaid: str
    paid: str
    rewardsPerShare: str


class RewardsLedgerItem(BaseModel):
    class Config:
        extra = Extra.forbid

    key: Key
    value: Value


class TokenPoolRewardStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    metadata: Dict[str, str]
    breakGlassConfig: BreakGlassConfig
    mvkTokenAddress: str
    governanceAddress: str
    whitelistContracts: Dict[str, str]
    generalContracts: Dict[str, str]
    whitelistTokenContracts: Dict[str, str]
    rewardsLedger: List[RewardsLedgerItem]
    lambdaLedger: Dict[str, str]
