# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict, List

from pydantic import BaseModel, Extra


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    blocksPerMinute: str
    farmNameMaxLength: str


class BreakGlassConfig(BaseModel):
    class Config:
        extra = Extra.forbid

    createFarmIsPaused: bool
    trackFarmIsPaused: bool
    untrackFarmIsPaused: bool


class FarmFactoryStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    metadata: Dict[str, str]
    mvkTokenAddress: str
    governanceAddress: str
    config: Config
    breakGlassConfig: BreakGlassConfig
    whitelistContracts: Dict[str, str]
    generalContracts: Dict[str, str]
    trackedFarms: List[str]
    lambdaLedger: Dict[str, str]
    farmLambdaLedger: Dict[str, str]
