# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict, List

from pydantic import BaseModel, Extra


class BreakGlassConfig(BaseModel):
    class Config:
        extra = Extra.forbid

    createFarmIsPaused: bool
    trackFarmIsPaused: bool
    untrackFarmIsPaused: bool


class FarmFactoryStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    blocksPerMinute: str
    breakGlassConfig: BreakGlassConfig
    generalContracts: Dict[str, str]
    mvkTokenAddress: str
    trackedFarms: List[str]
    whitelistContracts: Dict[str, str]
