# generated by datamodel-codegen:
#   filename:  snapshotLedger_value.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Extra


class SnapshotLedgerValue(BaseModel):
    class Config:
        extra = Extra.forbid

    totalStakedMvkBalance: str
    totalDelegatedAmount: str
    totalVotingPower: str
    accumulatedRewardsPerShare: str
    ready: bool
    nextSnapshotCycleId: Optional[str]
