---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dipdup
  labels:
    app: dipdup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dipdup
  template:
    metadata:
      labels:
        app: dipdup
    spec:
      imagePullSecrets:
        - name: docker-pull-credentials
      initContainers:
        - name: empty-db
          args: ['-c', 'dipdup.yml', 'schema', 'wipe', '--force']
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: indexer
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: indexer
                  key: POSTGRES_PORT
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: indexer
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: indexer
                  key: POSTGRES_PASSWORD
            - name: ADMIN_SECRET
              valueFrom:
                secretKeyRef:
                  name: indexer
                  key: HASURA_GRAPHQL_ADMIN_SECRET
            - name: TZKT_URL
              value: https://api.hangzhou2net.tzkt.io
          image: tezosdynamics/mavryk-indexer:v0.0.9
          imagePullPolicy: Always
          volumeMounts:
            - name: config-volume
              mountPath: /mavryk/dipdup.yml
              subPath: dipdup.yml
      containers:
        - name: dipdup
          args: ['-c', 'dipdup.yml', 'run']
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: indexer
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: indexer
                  key: POSTGRES_PORT
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: indexer
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: indexer
                  key: POSTGRES_PASSWORD
            - name: ADMIN_SECRET
              valueFrom:
                secretKeyRef:
                  name: indexer
                  key: HASURA_GRAPHQL_ADMIN_SECRET
            - name: TZKT_URL
              value: https://api.hangzhou2net.tzkt.io
          image: tezosdynamics/mavryk-indexer:v0.0.9
          imagePullPolicy: Always
          volumeMounts:
            - name: config-volume
              mountPath: /mavryk/dipdup.yml
              subPath: dipdup.yml
      volumes:
        - name: config-volume
          configMap:
            name: dipdup-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dipdup-config
data:
  dipdup.yml: |
    spec_version: 1.2
    package: mavryk

    database:
      kind: postgres
      host: ${POSTGRES_HOST:-changeme}
      port: ${POSTGRES_PORT:-changeme}
      user: ${POSTGRES_USERNAME:-changeme}
      password: ${POSTGRES_PASSWORD:-changeme}
      database: dipdup
      schema_name: public

    hasura:
      url: http://hasura.mavryk-indexer.svc.cluster.local:8080
      admin_secret: ${ADMIN_SECRET:-changeme}
      select_limit: 1000

    contracts:
      mvk:
        address: KT1CfB2hLU6oZpnFsuSw77aLanDEFPJjJtmW
        typename: mvk
      doorman:
        address: KT1NYRHupHBMDLdChrweYuKfuFTJttbWP3ua
        typename: doorman
      farm:
        address: KT1CazyJDLTCAYp4UXzzGFtN382V5NtAofBL
        typename: farm
      farm_factory:
        address: KT1TDe5Jh18wiNkoKW223L6oFvd4LV88u8yi
        typename: farm_factory
      delegation:
        address: KT1Nv9w4tShibfmyQc9hrZzwVnWZUJAgNYYn
        typename: delegation
      vesting:
        address: KT1Hzo5zQGSg18V1mPJ6umt7fmJq54MAF2ks
        typename: vesting
      emergency_governance:
        address: KT1By7RvnByUULr6TQABJ9CwHZwxDb6bmpVD
        typename: emergency_governance
      council:
        address: KT1EmLaLkxmK92oMBbcU934DgbF1ChYXQwjr
        typename: council

    datasources:
      tzkt:
        kind: tzkt
        url: ${TZKT_URL:-changeme}

    templates:
      farm_template:
        kind: operation
        datasource: tzkt
        types:
          - origination
          - transaction
        contracts:
          - <farm_contract>
        handlers:
          - callback: on_farm_origination
            pattern:
              - type: origination
                originated_contract: <farm_contract>
          - callback: on_farm_init_farm
            pattern:
              - destination: <farm_contract>
                entrypoint: initFarm
          - callback: on_farm_deposit
            pattern:
              - destination: <farm_contract>
                entrypoint: deposit
          - callback: on_farm_withdraw
            pattern:
              - destination: <farm_contract>
                entrypoint: withdraw
          - callback: on_farm_claim
            pattern:
              - destination: <farm_contract>
                entrypoint: claim
          - callback: on_farm_close_farm
            pattern:
              - destination: <farm_contract>
                entrypoint: closeFarm
          - callback: on_farm_increase_reward_per_block
            pattern:
              - destination: <farm_contract>
                entrypoint: increaseRewardPerBlock
          - callback: on_farm_toggle_force_reward_from_transfer
            pattern:
              - destination: <farm_contract>
                entrypoint: toggleForceRewardFromTransfer
          - callback: on_farm_pause_all
            pattern:
              - destination: <farm_contract>
                entrypoint: pauseAll
          - callback: on_farm_unpause_all
            pattern:
              - destination: <farm_contract>
                entrypoint: unpauseAll
          - callback: on_farm_toggle_pause_deposit
            pattern:
              - destination: <farm_contract>
                entrypoint: togglePauseDeposit
          - callback: on_farm_toggle_pause_withdraw
            pattern:
              - destination: <farm_contract>
                entrypoint: togglePauseWithdraw
          - callback: on_farm_toggle_pause_claim
            pattern:
              - destination: <farm_contract>
                entrypoint: togglePauseClaim

    indexes:
      # MVK Token contract indexes
      mvk:
        kind: operation
        datasource: tzkt
        types:
          - origination
          - transaction
        contracts:
          - mvk
        handlers:
          - callback: on_mvk_origination
            pattern:
              - type: origination
                originated_contract: mvk
          - callback: on_mvk_update_operators
            pattern:
              - destination: mvk
                entrypoint: update_operators
          - callback: on_mvk_transfer
            pattern:
              - destination: mvk
                entrypoint: transfer
          - callback: on_mvk_mint
            pattern:
              - destination: mvk
                entrypoint: mint
      # Doorman contract indexes
      doorman:
        kind: operation
        datasource: tzkt
        types:
          - origination
          - transaction
        contracts:
          - doorman
          - mvk
        handlers:
          - callback: on_doorman_origination
            pattern:
              - type: origination
                originated_contract: doorman
          - callback: on_doorman_stake
            pattern:
              - destination: doorman
                entrypoint: stake
              - source: doorman
                destination: mvk
                entrypoint: transfer
          - callback: on_doorman_unstake_complete
            pattern:
              - destination: doorman
                entrypoint: unstakeComplete
              - source: doorman
                destination: mvk
                entrypoint: transfer
          - callback: on_doorman_compound
            pattern:
              - destination: doorman
                entrypoint: compound
          - callback: on_doorman_farm_claim_complete
            pattern:
              - destination: doorman
                entrypoint: farmClaimComplete
          - callback: on_doorman_update_min_mvk_amount
            pattern:
              - destination: doorman
                entrypoint: updateMinMvkAmount
          - callback: on_doorman_farm_claim_complete
            pattern:
              - destination: doorman
                entrypoint: farmClaimComplete
          - callback: on_doorman_pause_all
            pattern:
              - destination: doorman
                entrypoint: pauseAll
          - callback: on_doorman_unpause_all
            pattern:
              - destination: doorman
                entrypoint: unpauseAll
          - callback: on_doorman_toggle_pause_stake
            pattern:
              - destination: doorman
                entrypoint: togglePauseStake
          - callback: on_doorman_toggle_pause_unstake
            pattern:
              - destination: doorman
                entrypoint: togglePauseUnstake
          - callback: on_doorman_toggle_pause_compound
            pattern:
              - destination: doorman
                entrypoint: togglePauseCompound
      # Farm contract indexes
      farm:
        kind: operation
        datasource: tzkt
        types:
          - origination
          - transaction
        contracts:
          - farm
        handlers:
          - callback: on_farm_origination
            pattern:
              - type: origination
                originated_contract: farm
          - callback: on_farm_init_farm
            pattern:
              - destination: farm
                entrypoint: initFarm
          - callback: on_farm_deposit
            pattern:
              - destination: farm
                entrypoint: deposit
          - callback: on_farm_withdraw
            pattern:
              - destination: farm
                entrypoint: withdraw
          - callback: on_farm_claim
            pattern:
              - destination: farm
                entrypoint: claim
          - callback: on_farm_close_farm
            pattern:
              - destination: farm
                entrypoint: closeFarm
          - callback: on_farm_increase_reward_per_block
            pattern:
              - destination: farm
                entrypoint: increaseRewardPerBlock
          - callback: on_farm_toggle_force_reward_from_transfer
            pattern:
              - destination: farm
                entrypoint: toggleForceRewardFromTransfer
          - callback: on_farm_pause_all
            pattern:
              - destination: farm
                entrypoint: pauseAll
          - callback: on_farm_unpause_all
            pattern:
              - destination: farm
                entrypoint: unpauseAll
          - callback: on_farm_toggle_pause_deposit
            pattern:
              - destination: farm
                entrypoint: togglePauseDeposit
          - callback: on_farm_toggle_pause_withdraw
            pattern:
              - destination: farm
                entrypoint: togglePauseWithdraw
          - callback: on_farm_toggle_pause_claim
            pattern:
              - destination: farm
                entrypoint: togglePauseClaim
      # Farm Factory contract indexes
      farm_factory:
        kind: operation
        datasource: tzkt
        types:
          - origination
          - transaction
        contracts:
          - farm_factory
        handlers:
          - callback: on_farm_factory_origination
            pattern:
              - type: origination
                originated_contract: farm_factory
          - callback: on_farm_factory_create_farm
            pattern:
              - destination: farm_factory
                entrypoint: createFarm
          - callback: on_farm_factory_track_farm
            pattern:
              - destination: farm_factory
                entrypoint: trackFarm
          - callback: on_farm_factory_pause_all
            pattern:
              - destination: farm_factory
                entrypoint: pauseAll
          - callback: on_farm_factory_unpause_all
            pattern:
              - destination: farm_factory
                entrypoint: unpauseAll
          - callback: on_farm_factory_toggle_pause_create_farm
            pattern:
              - destination: farm_factory
                entrypoint: togglePauseCreateFarm
          - callback: on_farm_factory_toggle_pause_track_farm
            pattern:
              - destination: farm_factory
                entrypoint: togglePauseTrackFarm
          - callback: on_farm_factory_toggle_pause_untrack_farm
            pattern:
              - destination: farm_factory
                entrypoint: togglePauseUntrackFarm
      # Delegation contract indexes
      delegation:
        kind: operation
        datasource: tzkt
        types:
          - origination
          - transaction
        contracts:
          - delegation
        handlers:
          - callback: on_delegation_origination
            pattern:
              - type: origination
                originated_contract: delegation
          - callback: on_delegation_update_config
            pattern:
              - destination: delegation
                entrypoint: updateConfig
          - callback: on_delegation_delegate_to_satellite
            pattern:
              - destination: delegation
                entrypoint: delegateToSatellite
          - callback: on_delegation_undelegate_from_satellite
            pattern:
              - destination: delegation
                entrypoint: undelegateFromSatelliteComplete
          - callback: on_delegation_register_as_satellite_complete
            pattern:
              - destination: delegation
                entrypoint: registerAsSatelliteComplete
          - callback: on_delegation_unregister_as_satellite
            pattern:
              - destination: delegation
                entrypoint: unregisterAsSatellite
          - callback: on_delegation_update_satellite_record
            pattern:
              - destination: delegation
                entrypoint: updateSatelliteRecord
          - callback: on_delegation_toggle_pause_delegate_to_satellite
            pattern:
              - destination: delegation
                entrypoint: togglePauseDelegateToSatellite
          - callback: on_delegation_toggle_pause_undelegate_satellite
            pattern:
              - destination: delegation
                entrypoint: togglePauseUndelegateSatellite
          - callback: on_delegation_toggle_pause_register_satellite
            pattern:
              - destination: delegation
                entrypoint: togglePauseRegisterSatellite
          - callback: on_delegation_toggle_pause_unregister_satellite
            pattern:
              - destination: delegation
                entrypoint: togglePauseUnregisterSatellite
          - callback: on_delegation_toggle_pause_update_satellite
            pattern:
              - destination: delegation
                entrypoint: togglePauseDelegateToSatellite
          - callback: on_delegation_pause_all
            pattern:
              - destination: delegation
                entrypoint: pauseAll
          - callback: on_delegation_unpause_all
            pattern:
              - destination: delegation
                entrypoint: unpauseAll
      # Vesting contract indexes
      vesting:
        kind: operation
        datasource: tzkt
        types:
          - origination
          - transaction
        contracts:
          - vesting
        handlers:
          - callback: on_vesting_origination
            pattern:
              - type: origination
                originated_contract: vesting
          - callback: on_vesting_update_config
            pattern:
              - destination: vesting
                entrypoint: updateConfig
          - callback: on_vesting_add_vestee
            pattern:
              - destination: vesting
                entrypoint: addVestee
          - callback: on_vesting_remove_vestee
            pattern:
              - destination: vesting
                entrypoint: removeVestee
          - callback: on_vesting_claim
            pattern:
              - destination: vesting
                entrypoint: claim
          - callback: on_vesting_toggle_vestee_lock
            pattern:
              - destination: vesting
                entrypoint: toggleVesteeLock
          - callback: on_vesting_update_vestee
            pattern:
              - destination: vesting
                entrypoint: updateVestee
      # Emergency Governance contract indexes
      emergency_governance:
        kind: operation
        datasource: tzkt
        types:
          - origination
          - transaction
        contracts:
          - emergency_governance
        handlers:
          - callback: on_emergency_governance_origination
            pattern:
              - type: origination
                originated_contract: emergency_governance
      # Council contract indexes
      council:
        kind: operation
        datasource: tzkt
        types:
          - origination
          - transaction
        contracts:
          - council
        handlers:
          - callback: on_council_origination
            pattern:
              - type: origination
                originated_contract: council
          - callback: on_council_update_config
            pattern:
              - destination: council
                entrypoint: updateConfig
          - callback: on_council_council_action_add_member
            pattern:
              - destination: council
                entrypoint: councilActionAddMember
          - callback: on_council_council_action_add_vestee
            pattern:
              - destination: council
                entrypoint: councilActionAddVestee
          - callback: on_council_council_action_change_member
            pattern:
              - destination: council
                entrypoint: councilActionChangeMember
