---
apiVersion: v1
kind: Service
metadata:
  name: dipdup-prometheus-{{ .Release.Name }}
  labels:
    app: dipdup-{{ .Release.Name }}
spec:
  ports:
    - name: metrics
      port: 9090
      protocol: TCP
      targetPort: metrics
  selector:
    app: dipdup-{{ .Release.Name }}
  type: ClusterIP
---
# Source: indexer-mavryk/charts/sealed-secrets/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dipdup-{{ .Release.Name }}
  namespace: kube-prometheus-stack #{ { .Values.dipdup.metrics.serviceMonitor.namespace } }
  labels:
    release: 'prod'
spec:
  endpoints:
    - honorLabels: true
      port: metrics
  namespaceSelector:
    matchNames:
      - mavryk-indexer
  selector:
    matchLabels:
      app: dipdup-{{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dipdup-{{ .Release.Name }}
  labels:
    app: dipdup-{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dipdup-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: dipdup-{{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: "{{ .Values.dipdup.image.pullSecret }}"
      containers:
        - name: dipdup-{{ .Release.Name }}
          args: ['-c', 'dipdup.yml', 'run']
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: indexer
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: indexer
                  key: POSTGRES_PORT
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: indexer
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: indexer
                  key: POSTGRES_PASSWORD
            - name: ADMIN_SECRET
              valueFrom:
                secretKeyRef:
                  name: indexer
                  key: HASURA_GRAPHQL_ADMIN_SECRET
            - name: TZKT_TESTNET_URL
              value: https://api.ghostnet.tzkt.io
            - name: TZKT_MAINNET_URL
              value: https://api.tzkt.io
          image: '{{ .Values.dipdup.image.registry }}/{{ .Values.dipdup.image.repository }}:{{ .Values.dipdup.image.tag }}'
          imagePullPolicy: '{{ .Values.dipdup.image.pullPolicy }}'
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /mavryk/dipdup.yml
              subPath: dipdup.yml
      volumes:
        - name: config-volume
          configMap:
            name: 'dipdup-{{ .Release.Name }}-config'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: 'dipdup-{{ .Release.Name }}-config'
data:
  dipdup.yml: |
    spec_version: 1.2
    package: mavryk
    
    database:
      kind: postgres
      host: ${POSTGRES_HOST:-changeme}
      port: ${POSTGRES_PORT:-changeme}
      user: ${POSTGRES_USERNAME:-changeme}
      password: ${POSTGRES_PASSWORD:-changeme}
      database: {{ .Values.dipdup.database.name }}
      schema_name: public
    
    hasura:
      url: http://hasura-{{ .Release.Name }}.mavryk-indexer.svc.cluster.local:8080
      admin_secret: ${ADMIN_SECRET:-changeme}
      select_limit: 1000
    
    prometheus:
      host: 0.0.0.0
      port: 9090
      update_interval: 5
      
    advanced:
      reindex:
        manual: wipe
        migration: exception
        rollback: ignore
        config_modified: wipe
        schema_modified: wipe
  {{- with .Values.dipdup.extraConfig }}
    {{ tpl . $ | nindent 4 }}
  {{- end }}
