{{- range $key, $value := .Values.instances }}
{{- if $value.dipdup.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: dipdup-prometheus-{{ $key }}
  labels:
    app: dipdup-{{ $key }}
spec:
  ports:
    - name: metrics
      port: 9090
      protocol: TCP
      targetPort: metrics
  selector:
    app: dipdup-{{ $key }}
  type: ClusterIP
---
# Source: indexer-mavryk/charts/sealed-secrets/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dipdup-{{ $key }}
  namespace: kube-prometheus-stack #{ { $value.dipdup.metrics.serviceMonitor.namespace } }
  labels:
    release: 'prod'
spec:
  endpoints:
    - honorLabels: true
      port: metrics
  namespaceSelector:
    matchNames:
      - mavryk-indexer
  selector:
    matchLabels:
      app: dipdup-{{ $key }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dipdup-{{ $key }}
  labels:
    app: dipdup-{{ $key }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dipdup-{{ $key }}
  template:
    metadata:
      labels:
        app: dipdup-{{ $key }}
    spec:
      imagePullSecrets:
        - name: '{{ $value.dipdup.image.pullSecret }}'
      containers:
        - name: dipdup-{{ $key }}
          args: ['-c', 'dipdup.yml', 'run']
          env:
          {{- range $value.dipdup.env }}
            - name: {{ .name }}
              {{- if ((.value))}}
              value: "{{.value}}"
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .valueFrom.secretKeyRef.name }}
                  key: {{ .valueFrom.secretKeyRef.key }}
              {{- end }}
          {{- end }}
          image: '{{ $value.dipdup.image.registry }}/{{ $value.dipdup.image.repository }}:{{ $value.dipdup.image.tag }}'
          imagePullPolicy: '{{ $value.dipdup.image.pullPolicy }}'
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
{{- end }}
{{- end }}
