apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prod2-pgadmin4
  namespace: mavryk-indexer
spec:
  encryptedData:
    password: AgAiTcT8UNo5S71O0vZ+bhTRoiD0PyjOXs06beWIIx95cnHcpSfnjf/nJQvhUbcx8R1++7qNbSU51OchMwAjwZ3ZsJBXMJF2AjM4LkKOGvWhrdem+9/K0XXbXnJfq5PFRTBuUdyTWPZxMerxX1GViGrqKyqhWN/9kfILT3wFXi+rRYBVz+E23SfS6O9kVqJQlV4e4Hf12l/1Ar58FKStNaJ3ctJebJaSNUu8wQk9BSRXI155rbq9Hy5qmLJQ/Xwlk+nY2dCugu012UBPeyBdM78Uw89FpWAr1YPDt+Z96dSlxL9gs8XOhTjsoTIKBcjxrkuRfkUGWrZQIUghPffWCqGocQp7Zou8O2zEpmNknsILo0EvImxIo1kzAAy9ZHNwUyU48ro3KGaX5VFxEZvdlXJcpb+on0r7gc7K5SWm/en/mhv9cDbHSZraWIlzaNHrd9ev9ScOWQwzFYsVUsEGEIx3mXmUB5A8J77CpadxTHirKGYwo4Y9z7ZFZiEwmor2ygXXdtLMPZscUE4lWIEOZota9WcNkkoSPahnR4tGFSAxazn8NwqX+uH8CoNJc9PEgSHIiNF9LsTIrdoud8AMQ5x/bhTnyJCgkDoOzRWUzzgGuCMBGE4VPUe8rnrXkkvSWr6CklBpYIdYOPv8wSr3ky0pOpDYjMQlt6g6RVd6Kzj4ygGcxcFxbFY/FK8DhK8VHO2PpLcQj6WkcoTtYKz2k2Zdpg==
    servers.json: AgAgmw6jI4iHuDhbq1oMZCOiT1hRpjnfYBADNF+teRS+ztnc+rH2sW5aC9NILBUiKxotnk//UGt9KDfPhkdUs0qzwkm6Bb3PoGKeTZx9YRogcBDabwni25nqRfsBemct/mvRX1WCAO3kLL2VG6iqL49oDs3PcaAIro/2Oz5Bspjjp2H98bMPozY5+P1/nEeT5NfZA2wWBW86wxmLHYBhYAMSZoK4+eiR9miaA60SRDkicOSQoxP1yYxOrjqQQ5JpbCH5N5I6Rqo8rj6D9m0Lb+9XGzqkziJEYPhuOxwihJjjrOGc0wajRoYJYavLcisIzr81PWZCHXGDfbirzoCCLCcpC0OfRFjil8kMWDZnOHUF/eu4ETP2J6E8GhcFjGRyhDGuQRKNd8fEHOfUj8s8hUYkgGorbsyn+gjvsxEryEY42EV+el2JI6nk+MFWqtLWUq9BD2e4kg2PsNgqA6r+rh8hSfC9F/hC63FTHFSbs9kP6qHO6Xun+d63vzKkBX99umZrYp8L+n3l9EIMPCK5ioXzpuvBrT2jAWmJoWkIs4sj5WtQBZSgKwe5/1j+z0cmaOvhAZSCCgSUL6Ejadm5w5/WexYwd9fNV43dvVIdFrEiYa++T3MRzh881pdNt8vJ6uPD0UeOlvMA2aLvU7awu0S4lGUWvwd1nRDxK9v+nAcJV+MwUEekND99Uev/XWiwqwzV9p4kXOMzpAFItD/f94wchxdCtJlQvCsvlWLzsi1c/yvZsAWF5Pu62yA2zZvB7wrZReqazDAXPKo0VZnerPADsGyGTEMd74k++9jkbYKlbXRzLhyVRJrm1eAKqe4yigY8A8xZTDCatjmv9Hiq7GWZJf3YxBXX5OOUkCCgE+yaI/nxL4r4ICKFlf7CAoMYpiBeiS/NQzDsd0xfKObwNxU=
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: pgadmin4
        app.kubernetes.io/version: "6.10"
        helm.sh/chart: pgadmin4-1.11.0
      name: prod2-pgadmin4
      namespace: mavryk-indexer
    type: Opaque

