# generated by datamodel-codegen:
#   filename:  requestMvk.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class RequestMvkParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
