# generated by datamodel-codegen:
#   filename:  addUpdateProposalData.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class AddUpdateProposalDataParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    proposalId: str
    title: str
    proposalBytes: str
