# generated by datamodel-codegen:
#   filename:  executeProposal.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class ExecuteProposalParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
