# generated by datamodel-codegen:
#   filename:  processProposalSingleData.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class ProcessProposalSingleDataParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
