# generated by datamodel-codegen:
#   filename:  propose.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class ProposeParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    title: str
    description: str
    invoice: str
    sourceCode: str
