# generated by datamodel-codegen:
#   filename:  requestSatelliteSnapshot.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class RequestSatelliteSnapshotParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    satelliteAddress: str
    requestId: str
    stakedMvkBalance: str
    totalDelegatedAmount: str
