# generated by datamodel-codegen:
#   filename:  requestStakedMvkSnapshot.json

from __future__ import annotations

from pydantic import BaseModel


class RequestStakedMvkSnapshotParameter(BaseModel):
    __root__: str
