# generated by datamodel-codegen:
#   filename:  setupLambdaFunction.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class SetupLambdaFunctionParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    id: str
    func_bytes: str
