# generated by datamodel-codegen:
#   filename:  startProposalRound.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class StartProposalRoundParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
