# generated by datamodel-codegen:
#   filename:  startTimelockRound.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class StartTimelockRoundParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
