# generated by datamodel-codegen:
#   filename:  startVotingRound.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class StartVotingRoundParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
