# generated by datamodel-codegen:
#   filename:  updatePaymentData.json

from __future__ import annotations

from typing import Any, Dict, Union

from pydantic import BaseModel, Extra


class TokenItem(BaseModel):
    class Config:
        extra = Extra.forbid

    fa12: str


class Fa2(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenContractAddress: str
    tokenId: str


class TokenItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    fa2: Fa2


class TokenItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    tez: Dict[str, Any]


class PaymentTransaction(BaseModel):
    class Config:
        extra = Extra.forbid

    to_: str
    token: Union[TokenItem, TokenItem1, TokenItem2]
    amount: str


class UpdatePaymentDataParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    proposalId: str
    title: str
    paymentTransaction: PaymentTransaction
