# generated by datamodel-codegen:
#   filename:  updateConfig.json

from __future__ import annotations

from typing import Any, Dict, Union

from pydantic import BaseModel, Extra


class UpdateConfigActionItem(BaseModel):
    class Config:
        extra = Extra.forbid

    configBlocksPerMinute: Dict[str, Any]


class UpdateConfigActionItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    configBlocksPerProposalRound: Dict[str, Any]


class UpdateConfigActionItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    configBlocksPerTimelockRound: Dict[str, Any]


class UpdateConfigActionItem3(BaseModel):
    class Config:
        extra = Extra.forbid

    configBlocksPerVotingRound: Dict[str, Any]


class UpdateConfigActionItem4(BaseModel):
    class Config:
        extra = Extra.forbid

    configMaxProposalsPerDelegate: Dict[str, Any]


class UpdateConfigActionItem5(BaseModel):
    class Config:
        extra = Extra.forbid

    configMinQuorumMvkTotal: Dict[str, Any]


class UpdateConfigActionItem6(BaseModel):
    class Config:
        extra = Extra.forbid

    configMinQuorumPercentage: Dict[str, Any]


class UpdateConfigActionItem7(BaseModel):
    class Config:
        extra = Extra.forbid

    configMinimumStakeReqPercentage: Dict[str, Any]


class UpdateConfigActionItem8(BaseModel):
    class Config:
        extra = Extra.forbid

    configNewBlockTimeLevel: Dict[str, Any]


class UpdateConfigActionItem9(BaseModel):
    class Config:
        extra = Extra.forbid

    configNewBlocksPerMinute: Dict[str, Any]


class UpdateConfigActionItem10(BaseModel):
    class Config:
        extra = Extra.forbid

    configProposalSubmissionFee: Dict[str, Any]


class UpdateConfigActionItem11(BaseModel):
    class Config:
        extra = Extra.forbid

    configSuccessReward: Dict[str, Any]


class UpdateConfigActionItem12(BaseModel):
    class Config:
        extra = Extra.forbid

    configVotingPowerRatio: Dict[str, Any]


class UpdateConfigParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    updateConfigNewValue: str
    updateConfigAction: Union[
        UpdateConfigActionItem,
        UpdateConfigActionItem1,
        UpdateConfigActionItem2,
        UpdateConfigActionItem3,
        UpdateConfigActionItem4,
        UpdateConfigActionItem5,
        UpdateConfigActionItem6,
        UpdateConfigActionItem7,
        UpdateConfigActionItem8,
        UpdateConfigActionItem9,
        UpdateConfigActionItem10,
        UpdateConfigActionItem11,
        UpdateConfigActionItem12,
    ]
