# generated by datamodel-codegen:
#   filename:  updateProposalData.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class UpdateProposalDataParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    proposalId: str
    title: str
    proposalBytes: str
