# generated by datamodel-codegen:
#   filename:  updateSatelliteSnapshot.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class SatelliteRecord(BaseModel):
    class Config:
        extra = Extra.forbid

    status: str
    stakedMvkBalance: str
    satelliteFee: str
    totalDelegatedAmount: str
    name: str
    description: str
    image: str
    website: str
    registeredDateTime: str


class UpdateSatelliteSnapshotParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    satelliteAddress: str
    satelliteRecord: SatelliteRecord
    ready: bool
    delegationRatio: str
