# generated by datamodel-codegen:
#   filename:  setLoanToken.json

from __future__ import annotations

from typing import Any, Dict, Union

from pydantic import BaseModel, Extra


class TokenTypeItem(BaseModel):
    class Config:
        extra = Extra.forbid

    fa12: str


class Fa2(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenContractAddress: str
    tokenId: str


class TokenTypeItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    fa2: Fa2


class TokenTypeItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    tez: Dict[str, Any]


class SetLoanTokenParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenName: str
    tokenDecimals: str
    oracleType: str
    oracleAddress: str
    lpTokenContractAddress: str
    lpTokenId: str
    reserveRatio: str
    optimalUtilisationRate: str
    baseInterestRate: str
    maxInterestRate: str
    interestRateBelowOptimalUtilisation: str
    interestRateAboveOptimalUtilisation: str
    minRepaymentAmount: str
    tokenType: Union[TokenTypeItem, TokenTypeItem1, TokenTypeItem2]
