# generated by datamodel-codegen:
#   filename:  vaultDepositStakedMvk.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class VaultDepositStakedMvkParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    vaultId: str
    depositAmount: str
