# generated by datamodel-codegen:
#   filename:  createAggregator.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, Extra


class AggregatorConfig(BaseModel):
    class Config:
        extra = Extra.forbid

    decimals: str
    numberBlocksDelay: str
    deviationTriggerBanDuration: str
    perThousandDeviationTrigger: str
    percentOracleThreshold: str
    requestRateDeviationDepositFee: str
    deviationRewardStakedMvk: str
    deviationRewardAmountXtz: str
    rewardAmountStakedMvk: str
    rewardAmountXtz: str


class CreateAggregatorParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    string_0: str
    string_1: str
    name: str
    addToGeneralContracts: bool
    oracleAddresses: Dict[str, bool]
    aggregatorConfig: AggregatorConfig
    maintainer: str
    metadata: str
