# generated by datamodel-codegen:
#   filename:  distributeRewardXtz.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class DistributeRewardXtzParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    recipient: str
    reward: str
