# generated by datamodel-codegen:
#   filename:  distributeRewardStakedMvk.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Extra


class DistributeRewardStakedMvkParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    eligibleSatellites: List[str]
    totalStakedMvkReward: str
