# generated by datamodel-codegen:
#   filename:  togglePauseCreateAggregator.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TogglePauseCreateAggregatorParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
