# generated by datamodel-codegen:
#   filename:  togglePauseDistributeRewardSMvk.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TogglePauseDistributeRewardSMvkParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
