# generated by datamodel-codegen:
#   filename:  togglePauseUntrackAggregator.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TogglePauseUntrackAggregatorParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
