# generated by datamodel-codegen:
#   filename:  togglePauseDistributeRewardXtz.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TogglePauseDistributeRewardXtzParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
