# generated by datamodel-codegen:
#   filename:  togglePauseTrackAggregator.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TogglePauseTrackAggregatorParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
