# generated by datamodel-codegen:
#   filename:  trackAggregator.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TrackAggregatorParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    pairFirst: str
    pairSecond: str
    aggregatorAddress: str
