# generated by datamodel-codegen:
#   filename:  untrackAggregator.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class UntrackAggregatorParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    pairFirst: str
    pairSecond: str
