# generated by datamodel-codegen:
#   filename:  setCollateralToken.json

from __future__ import annotations

from typing import Any, Dict, Optional, Union

from pydantic import BaseModel, Extra


class TokenType(BaseModel):
    class Config:
        extra = Extra.forbid

    fa12: str


class Fa2(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenContractAddress: str
    tokenId: str


class TokenType1(BaseModel):
    class Config:
        extra = Extra.forbid

    fa2: Fa2


class TokenType2(BaseModel):
    class Config:
        extra = Extra.forbid

    mav: Dict[str, Any]


class CreateCollateralToken(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenName: str
    tokenContractAddress: str
    tokenDecimals: str
    oracleAddress: str
    protected: bool
    isScaledToken: bool
    isStakedToken: bool
    stakingContractAddress: Optional[str]
    maxDepositAmount: Optional[str]
    tokenType: Union[TokenType, TokenType1, TokenType2]


class ActionItem(BaseModel):
    class Config:
        extra = Extra.forbid

    createCollateralToken: CreateCollateralToken


class UpdateCollateralToken(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenName: str
    oracleAddress: str
    isPaused: bool
    stakingContractAddress: Optional[str]
    maxDepositAmount: Optional[str]


class ActionItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    updateCollateralToken: UpdateCollateralToken


class SetCollateralTokenParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    action: Union[ActionItem, ActionItem1]
    empty: Dict[str, Any]
