# generated by datamodel-codegen:
#   filename:  updateGeneralContracts.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class UpdateGeneralContractsParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    generalContractName: str
    generalContractAddress: str
