# generated by datamodel-codegen:
#   filename:  vaultWithdrawStakedMvk.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class VaultWithdrawStakedMvkParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    vaultId: str
    withdrawAmount: str
