# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict, List

from pydantic import BaseModel, Extra


class BreakGlassConfig(BaseModel):
    class Config:
        extra = Extra.forbid

    createTreasuryIsPaused: bool
    trackTreasuryIsPaused: bool
    untrackTreasuryIsPaused: bool


class TreasuryFactoryStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    mvkTokenAddress: str
    governanceAddress: str
    metadata: Dict[str, str]
    trackedTreasuries: List[str]
    breakGlassConfig: BreakGlassConfig
    whitelistContracts: Dict[str, str]
    whitelistTokenContracts: Dict[str, str]
    generalContracts: Dict[str, str]
    lambdaLedger: Dict[str, str]
    treasuryLambdaLedger: Dict[str, str]
