export const breakGlassActions = {
  REMOVE_COUNCIL_MEMBER: 'REMOVE_COUNCIL_MEMBER',
  CHANGE_COUNCIL_MEMBER: 'CHANGE_COUNCIL_MEMBER',
  UPDATE_COUNCIL_MEMBER: 'UPDATE_COUNCIL_MEMBER',
  ADD_COUNCIL_MEMBER: 'ADD_COUNCIL_MEMBER',
}
