# generated by datamodel-codegen:
#   filename:  updateRewards.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class UpdateRewardsParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    loanTokenName: str
    userAddress: str
    depositorBalance: str
