# generated by datamodel-codegen:
#   filename:  createVault.json

from __future__ import annotations

from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Extra


class Depositor(BaseModel):
    class Config:
        extra = Extra.forbid

    any: Dict[str, Any]


class Depositor1(BaseModel):
    class Config:
        extra = Extra.forbid

    whitelist: List[str]


class CreateVaultParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    delegate: Optional[str]
    loanTokenName: str
    name: str
    depositors: Union[Depositor, Depositor1]
