# generated by datamodel-codegen:
#   filename:  togglePauseEntrypoint.json

from __future__ import annotations

from typing import Any, Dict, Union

from pydantic import BaseModel, Extra


class TargetEntrypointItem(BaseModel):
    class Config:
        extra = Extra.forbid

    createVault: bool


class TargetEntrypointItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    empty: Dict[str, Any]


class TogglePauseEntrypointParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    targetEntrypoint: Union[TargetEntrypointItem, TargetEntrypointItem1]
    empty: Dict[str, Any]
