# generated by datamodel-codegen:
<<<<<<< HEAD
#   filename:  onStakeChange.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Extra


class OnStakeChangeParameterItem(BaseModel):
    class Config:
        extra = Extra.forbid

    address: str
    nat: str


class OnStakeChangeParameter(BaseModel):
    __root__: List[OnStakeChangeParameterItem]
=======
#   filename:  burn.json

from __future__ import annotations

from pydantic import BaseModel


class BurnParameter(BaseModel):
    __root__: str
>>>>>>> 63661dace (handlers refactored for dipdup 7)
