# generated by datamodel-codegen:
#   filename:  setContractBaker.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Extra


class SetContractBakerParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    targetContractAddress: str
    keyHash: Optional[str]
