# generated by datamodel-codegen:
#   filename:  voteForRequest.json

from __future__ import annotations

from typing import Any, Dict, Union

from pydantic import BaseModel, Extra


class VoteItem(BaseModel):
    class Config:
        extra = Extra.forbid

    approve: Dict[str, Any]


class VoteItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    disapprove: Dict[str, Any]


class VoteForRequestParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    requestId: str
    vote: Union[VoteItem, VoteItem1]
