# generated by datamodel-codegen:
#   filename:  updateConfig.json

from __future__ import annotations

from typing import Any, Dict, Union

from pydantic import BaseModel, Extra


class UpdateConfigActionItem(BaseModel):
    class Config:
        extra = Extra.forbid

    configBlocksPerMinute: Dict[str, Any]


class UpdateConfigActionItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    configBlocksPerMonth: Dict[str, Any]


class UpdateConfigActionItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    configDefaultCliffPeriod: Dict[str, Any]


class UpdateConfigActionItem3(BaseModel):
    class Config:
        extra = Extra.forbid

    configDefaultCooldownPeriod: Dict[str, Any]


class UpdateConfigActionItem4(BaseModel):
    class Config:
        extra = Extra.forbid

    configNewBlockTimeLevel: Dict[str, Any]


class UpdateConfigActionItem5(BaseModel):
    class Config:
        extra = Extra.forbid

    configNewBlocksPerMinute: Dict[str, Any]


class UpdateConfigParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    updateConfigNewValue: str
    updateConfigAction: Union[
        UpdateConfigActionItem,
        UpdateConfigActionItem1,
        UpdateConfigActionItem2,
        UpdateConfigActionItem3,
        UpdateConfigActionItem4,
        UpdateConfigActionItem5,
    ]
