# generated by datamodel-codegen:
#   filename:  updateVestee.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class UpdateVesteeParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    address: str
    nat_0: str
    nat_1: str
    nat_2: str
