# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, Extra


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    aggregatorNameMaxLength: str
    empty: Dict[str, Any]


class BreakGlassConfig(BaseModel):
    class Config:
        extra = Extra.forbid

    createAggregatorIsPaused: bool
    trackAggregatorIsPaused: bool
    untrackAggregatorIsPaused: bool
    distributeRewardXtzIsPaused: bool
    distributeRewardMvkIsPaused: bool


class Key(BaseModel):
    class Config:
        extra = Extra.forbid

    string_0: str
    string_1: str


class TrackedAggregator(BaseModel):
    class Config:
        extra = Extra.forbid

    key: Key
    value: str


class AggregatorFactoryStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    metadata: Dict[str, str]
    config: Config
    mvkTokenAddress: str
    governanceAddress: str
    whitelistContracts: Dict[str, str]
    generalContracts: Dict[str, str]
    breakGlassConfig: BreakGlassConfig
    trackedAggregators: List[TrackedAggregator]
    lambdaLedger: Dict[str, str]
    aggregatorLambdaLedger: Dict[str, str]
