# generated by datamodel-codegen:
#   filename:  addCouncilMember.json

from __future__ import annotations

from pydantic import BaseModel


class AddCouncilMemberParameter(BaseModel):
    __root__: str
