# generated by datamodel-codegen:
#   filename:  addCouncilMember.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class AddCouncilMemberParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    memberAddress: str
    memberName: str
    memberWebsite: str
    memberImage: str
