# generated by datamodel-codegen:
#   filename:  setAllContractsAdmin.json

from __future__ import annotations

from pydantic import BaseModel


class SetAllContractsAdminParameter(BaseModel):
    __root__: str
