# generated by datamodel-codegen:
#   filename:  setSingleContractAdmin.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class SetSingleContractAdminParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    targetContractAddress: str
    newContractAdmin: str
