# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Any, Dict, List, Union

from pydantic import BaseModel, Extra


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    collateralRatio: str
    liquidationRatio: str
    liquidationFeePercent: str
    adminLiquidationFeePercent: str
    minimumLoanFeePercent: str
    minimumLoanFeeTreasuryShare: str
    interestTreasuryShare: str
    decimals: str
    interestRateDecimals: str
    maxDecimalsForCalculation: str
    maxVaultLiquidationPercent: str
    liquidationDelayInMins: str


class BreakGlassConfig(BaseModel):
    class Config:
        extra = Extra.forbid

    addLiquidityIsPaused: bool
    borrowIsPaused: bool
    claimRewardsIsPaused: bool
    closeVaultIsPaused: bool
    createVaultIsPaused: bool
    liquidateVaultIsPaused: bool
    markForLiquidationIsPaused: bool
    registerDepositIsPaused: bool
    registerWithdrawalIsPaused: bool
    removeLiquidityIsPaused: bool
    repayIsPaused: bool
    setLoanTokenIsPaused: bool
    updateCollateralTokenIsPaused: bool
    vaultDelegateMvkToSatelliteIsPaused: bool
    vaultDelegateTezToBakerIsPaused: bool
    vaultDepositIsPaused: bool
    vaultDepositStakedMvkIsPaused: bool
    vaultEditDepositorIsPaused: bool
    vaultLiquidateStakedMvkIsPaused: bool
    vaultWithdrawIsPaused: bool
    vaultWithdrawStakedMvkIsPaused: bool


class Key(BaseModel):
    class Config:
        extra = Extra.forbid

    address: str
    string: str


class Value(BaseModel):
    class Config:
        extra = Extra.forbid

    unpaid: str
    paid: str
    rewardsPerShare: str


class RewardsLedgerItem(BaseModel):
    class Config:
        extra = Extra.forbid

    key: Key
    value: Value


class Key1(BaseModel):
    class Config:
        extra = Extra.forbid

    address: str
    string: str


class TokenPoolDepositorLedgerItem(BaseModel):
    class Config:
        extra = Extra.forbid

    key: Key1
    value: str


class Key2(BaseModel):
    class Config:
        extra = Extra.forbid

    id: str
    owner: str


class Value1(BaseModel):
    class Config:
        extra = Extra.forbid

    address: str
    collateralBalanceLedger: Dict[str, str]
    loanToken: str
    loanOutstandingTotal: str
    loanPrincipalTotal: str
    loanInterestTotal: str
    loanDecimals: str
    borrowIndex: str
    lastUpdatedBlockLevel: str
    lastUpdatedTimestamp: str
    markedForLiquidationTimestamp: str


class Vault(BaseModel):
    class Config:
        extra = Extra.forbid

    key: Key2
    value: Value1


class TokenTypeItem(BaseModel):
    class Config:
        extra = Extra.forbid

    fa12: str


class Fa2(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenContractAddress: str
    tokenId: str


class TokenTypeItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    fa2: Fa2


class TokenTypeItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    tez: Dict[str, Any]


class CollateralTokenLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenName: str
    tokenContractAddress: str
    tokenDecimals: str
    oracleType: str
    oracleAddress: str
    tokenType: Union[TokenTypeItem, TokenTypeItem1, TokenTypeItem2]


class TokenTypeItem3(BaseModel):
    class Config:
        extra = Extra.forbid

    fa12: str


class Fa21(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenContractAddress: str
    tokenId: str


class TokenTypeItem4(BaseModel):
    class Config:
        extra = Extra.forbid

    fa2: Fa21


class TokenTypeItem5(BaseModel):
    class Config:
        extra = Extra.forbid

    tez: Dict[str, Any]


class LoanTokenLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenName: str
    tokenType: Union[TokenTypeItem3, TokenTypeItem4, TokenTypeItem5]
    tokenDecimals: str
    oracleType: str
    oracleAddress: str
    lpTokensTotal: str
    lpTokenContractAddress: str
    lpTokenId: str
    reserveRatio: str
    tokenPoolTotal: str
    totalBorrowed: str
    totalRemaining: str
    utilisationRate: str
    optimalUtilisationRate: str
    baseInterestRate: str
    maxInterestRate: str
    interestRateBelowOptimalUtilisation: str
    interestRateAboveOptimalUtilisation: str
    currentInterestRate: str
    lastUpdatedBlockLevel: str
    accumulatedRewardsPerShare: str
    borrowIndex: str
    minRepaymentAmount: str


class LendingControllerStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    metadata: Dict[str, str]
    config: Config
    breakGlassConfig: BreakGlassConfig
    mvkTokenAddress: str
    governanceAddress: str
    whitelistContracts: Dict[str, str]
    generalContracts: Dict[str, str]
    whitelistTokenContracts: Dict[str, str]
    rewardsLedger: List[RewardsLedgerItem]
    tokenPoolDepositorLedger: List[TokenPoolDepositorLedgerItem]
    vaults: List[Vault]
    vaultCounter: str
    ownerLedger: Dict[str, List[str]]
    collateralTokenLedger: Dict[str, CollateralTokenLedger]
    loanTokenLedger: Dict[str, LoanTokenLedger]
    lambdaLedger: Dict[str, str]
    vaultLambdaLedger: Dict[str, str]
    tempMap: Dict[str, str]
