{{- range $key, $val := .Values.deku.nodes }}
{{- if $val }}
  {{- $_ := set $ "node_class" $key }}
  {{- $_ := set $ "node_vals" $val }}
  {{- $_ := set $ "node_identities" dict }}

{{- $deku_validators := "" }}
{{- $deku_validators_uri := "" }}
{{- range $i, $e := $.Values.deku.nodes }}
{{- if $i }}
{{- $deku_validators = print $deku_validators $e.validator.publicKeyHash "," }}
{{- $deku_validators_uri = print $deku_validators_uri $i "." $.Release.Namespace ".svc.cluster.local:4440" "," }}
{{- end }}
{{- end }}

apiVersion: v1
kind: Service
metadata:
  name: {{ $.node_class }}
  labels:
    app: {{ $.node_class }}
spec:
  ports:
    - name: deku
      port: 4440
      protocol: TCP
      targetPort: deku
{{- if $.node_vals.api }}
    - name: api
      port: 8080
      protocol: TCP
      targetPort: api
{{- end }}
  selector:
    app: {{ $.node_class }}
  type: ClusterIP
{{- if $.node_vals.api }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.node_class }}
  namespace: {{ $.Release.Namespace }}
  annotations:
{{- $.node_vals.ingress.annotations | toYaml | nindent 4  }}
spec:
  tls:
    - hosts:
        - {{ $.node_vals.ingress.host }}
      secretName: {{ $.node_class }}-api-tls
  rules:
    - host: {{ $.node_vals.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.node_class }}
                port:
                  name: api
{{- end }}
---
{{- end }}
{{- end }}
