{{- range $key, $val := .Values.deku.nodes }}
{{- if $val }}
  {{- $_ := set $ "node_class" $key }}
  {{- $_ := set $ "node_vals" $val }}
  {{- $_ := set $ "node_identities" dict }}

{{- $deku_validators := "" }}
{{- $deku_validators_uri := "" }}
{{- range $i, $e := $.Values.deku.nodes }}
{{- if $i }}
{{- $deku_validators = print $deku_validators $e.validator.publicKeyHash "," }}
{{- $deku_validators_uri = print $deku_validators_uri $i "." $.Release.Namespace ".svc.cluster.local:4440" "," }}
{{- end }}
{{- end }}

apiVersion: v1
kind: Service
metadata:
  name: {{ $.node_class }}
  labels:
    app: {{ $.node_class }}
spec:
  ports:
    - name: deku
      port: 4440
      protocol: TCP
      targetPort: deku
{{- if $.node_vals.api }}
    - name: api
      port: 8080
      protocol: TCP
      targetPort: api
    - name: api-tcp
      port: 5550
      protocol: TCP
      targetPort: api-tcp
    - name: metrics
      port: 9090
      protocol: TCP
      targetPort: metrics
{{- end }}
  selector:
    app: {{ $.node_class }}
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $.node_class }}
  labels:
    app: {{ $.node_class }}
  namespace: {{ $.Release.Namespace }}
spec:
  podManagementPolicy: Parallel
  replicas: 1
  serviceName: {{ $.node_class }}
  selector:
    matchLabels:
      app: {{ $.node_class }}
  template:
    metadata:
      labels:
        app: {{ $.node_class }}
    spec:
      {{- if $.node_vals.nodeSelector }}
      nodeSelector:
        {{ $.node_vals.nodeSelector | toYaml }}
      {{- end }}
      {{- if $.node_vals.tolerations }}
      {{- range $key, $val := $.node_vals.tolerations }}
      tolerations:
        - key: "{{ $val.key }}"
          operator: "{{ $val.operator }}"
          value: "{{ $val.value }}"
          effect: "{{ $val.effect }}"
      {{- end }}
      {{- end }}
      imagePullSecrets:
        - name: {{ $.Values.dockerPullSecretName }}
      containers:
      {{- if $.node_vals.api }}
        - name: api
          env:
            - name: DEKU_API_DATABASE_URI
              value: '{{ $.node_vals.api.config.apiDatabaseUri }}'
            - name: DEKU_API_DATA_FOLDER
              value: '/var/deku-api'
            - name: DEKU_LOG_VERBOSITY
              value: 'debug'
            - name: DEKU_API_LOG_VERBOSITY
              value: 'debug'
            - name: DEKU_API_NODE_URI
              value: '{{ $.node_class }}.{{ $.Release.Namespace }}.svc.cluster.local:4440'
            - name: DEKU_API_PORT
              value: '8080'
            - name: DEKU_API_TCP_PORT
              value: '5550'
            - name: DEKU_API_DOMAINS
              value: '8'
            - name: DEKU_DEFAULT_BLOCK_SIZE
              value: '{{ $.Values.deku.config.defaultBlockSize }}'
            - name: DEKU_API_VM
              value: '/var/deku/api_vm_pipe'
            - name: DEKU_TEZOS_CONSENSUS_ADDRESS
              value: '{{ $.Values.deku.config.tezosConsensusAddress }}'
            - name: DEKU_DUMMYT_TICKET
              value: '{{ $.Values.deku.config.dummyTicketAddress }}'
            - name: DEKU_DUMMY_TICKET
              value: '{{ $.Values.deku.config.dummyTicketAddress }}'
            - name: DEKU_DUMMY_TICKET_CONTRACT
              value: '{{ $.Values.deku.config.dummyTicketAddress }}'
          image: '{{ $.node_vals.api.image.registry }}/{{ $.node_vals.api.image.repository }}:{{ $.node_vals.api.image.tag }}'
          imagePullPolicy: '{{ $.node_vals.api.image.pullPolicy }}'
          ports:
            - name: api
              containerPort: 80
              protocol: TCP
            - name: api-tcp
              containerPort: 5550
              protocol: TCP
          volumeMounts:
            - mountPath: /var/deku-api
              name: api-db-volume
        - name: prometheus
          env:
            - name: POLLING_INTERVAL_SECONDS
              value: '5'
            - name: APP_PORT
              value: '80'
            - name: EXPORTER_PORT
              value: '9090'
          image: '{{ $.node_vals.api.metrics.image.registry }}/{{ $.node_vals.api.metrics.image.repository }}:{{ $.node_vals.api.metrics.image.tag }}'
          imagePullPolicy: '{{ $.node_vals.api.metrics.image.pullPolicy }}'
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
        {{- end }}
        - name: deku
          env:
            - name: DEKU_VALIDATORS
              value: {{ regexReplaceAll "[,]$" $deku_validators "" }}
            - name: DEKU_VALIDATOR_URIS
              value: {{ regexReplaceAll "[,]$" $deku_validators_uri "" }}
            - name: DEKU_TEZOS_RPC_NODE
              value: '{{ $.node_vals.tezosRpcUrl }}'
            - name: DEKU_TEZOS_SECRET
              value: '{{ $.Values.deku.config.tezosSecret }}'
            - name: DEKU_TEZOS_CONSENSUS_ADDRESS
              value: '{{ $.Values.deku.config.tezosConsensusAddress }}'
            - name: DEKU_DUMMYT_TICKET
              value: '{{ $.Values.deku.config.dummyTicketAddress }}'
            - name: DEKU_DUMMY_TICKET
              value: '{{ $.Values.deku.config.dummyTicketAddress }}'
            - name: DEKU_DUMMY_TICKET_CONTRACT
              value: '{{ $.Values.deku.config.dummyTicketAddress }}'
            - name: DEKU_DEFAULT_BLOCK_SIZE
              value: '{{ $.Values.deku.config.defaultBlockSize }}'
            - name: DEKU_LOG_VERBOSITY
              value: 'debug'
            - name: DEKU_API_LOG_VERBOSITY
              value: 'debug'
            - name: DEKU_API_URI
              value: '{{ $.Values.deku.config.apiUri }}'
            - name: DEKU_DATA_FOLDER
              value: '/var/deku'
            - name: DEKU_DATABASE_URI
              value: '{{ $.Values.deku.config.databaseUri }}'
            - name: DEKU_DOMAINS
              value: '8'
            - name: DEKU_SECRET
              value: '{{ $.node_vals.validator.secretKey }}'
            - name: DEKU_PORT
              value: '4440'
          image: '{{ $.node_vals.image.registry }}/{{ $.node_vals.image.repository }}:{{ $.node_vals.image.tag }}'
          imagePullPolicy: '{{ $.node_vals.image.pullPolicy }}'
          ports:
            - name: deku
              containerPort: 4440
              protocol: TCP
          volumeMounts:
            - mountPath: /var/deku
              name: node-db-volume
      securityContext:
        fsGroup: 1000
  volumeClaimTemplates:
    {{- if $.node_vals.api }}
    - metadata:
        name: api-db-volume
        namespace: {{ $.Release.Namespace }}
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: do-block-storage
        resources:
          requests:
            storage: "5Gi"
    {{- end }}
    - metadata:
        name: node-db-volume
        namespace: {{ $.Release.Namespace }}
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: do-block-storage
        resources:
          requests:
            storage: "5Gi"
{{- if $.node_vals.api }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.node_class }}
  namespace: {{ $.Release.Namespace }}
  annotations:
{{- $.node_vals.ingress.annotations | toYaml | nindent 4  }}
spec:
  tls:
    - hosts:
        - {{ $.node_vals.ingress.host }}
      secretName: {{ $.node_class }}-api-tls
  rules:
    - host: {{ $.node_vals.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.node_class }}
                port:
                  name: api
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $.node_class }}
  namespace: kube-prometheus-stack
spec:
  endpoints:
    - honorLabels: true
      port: metrics
      path: /
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  selector:
    matchLabels:
      app: {{ $.node_class }}
{{- end }}
---
{{- end }}
{{- end }}
