{{- range $key, $val := .Values.nodes }}
{{- if $val }}
  {{- $_ := set $ "node_class" $key }}
  {{- $_ := set $ "node_vals" $val }}
  {{- $_ := set $ "node_identities" dict }}

  {{- include "tezos.includeNodeIdentitySecret" $ }}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $.node_class }}
  namespace: {{ $.Release.Namespace }}
spec:
  podManagementPolicy: Parallel
  replicas: {{ $.node_vals.instances | len }}
  serviceName: {{ $.node_class }}
  selector:
    matchLabels:
      node_class: {{ $.node_class }}
  template:
    metadata:
      labels:
        appType: octez-node
        node_class: {{ $.node_class }}
      {{- if has "baker" $.node_vals.runs }}
        baking_node: "true"
      {{- end }}
      {{- if $.node_vals.labels }}
        {{- $.node_vals.labels | toYaml | nindent 8 }}
      {{- end }}
    spec:
      {{- range $key, $val := $.node_vals.tolerations }}
      tolerations:
        - key: "{{ $val.key }}"
          operator: "{{ $val.operator }}"
          value: "{{ $val.value }}"
          effect: "{{ $val.effect }}"
      {{- end }}
      containers:
        {{- include "tezos.container.node"      $ | indent 8 }}
        {{- include "tezos.container.accusers"  $ | indent 8 }}
        {{- include "tezos.container.bakers"    $ | indent 8 }}
        {{- include "tezos.container.logger"    $ | indent 8 }}
        {{- include "tezos.container.zerotier"  $ | indent 8 }}
        {{- include "tezos.container.sidecar"   $ | indent 8 }}
        {{- include "tezos.container.vdf"       $ | indent 8 }}
      initContainers:
        {{- include "tezos.init_container.config_init"         $ | indent 8 }}
        {{- include "tezos.init_container.zerotier"            $ | indent 8 }}
        {{- include "tezos.init_container.config_generator"    $ | indent 8 }}
        {{- include "tezos.init_container.snapshot_downloader" $ | indent 8 }}
        {{- include "tezos.init_container.snapshot_importer"   $ | indent 8 }}
        {{- include "tezos.init_container.wait_for_dns"        $ | indent 8 }}
        {{- include "tezos.init_container.upgrade_storage"     $ | indent 8 }}
      securityContext:
        fsGroup: 1000
{{- include "tezos.nodeSelectorConfig" $ | indent 6 }}
      volumes:
        - hostPath:
            path: /dev/net/tun
          name: dev-net-tun
        - emptyDir: {}
          name: config-volume
        - name: tezos-accounts
          secret:
            secretName: tezos-secret
{{- if (include "tezos.hasPerBlockVotes" $) }}
        - name: per-block-votes
          configMap:
            name: per-block-votes
{{- end }}
{{- if $.node_vals.local_storage | default false }}
        - emptyDir: {}
          name: var-volume
{{- else }}
  volumeClaimTemplates:
    - metadata:
        name: var-volume
        namespace: {{ $.Release.Namespace }}
      spec:
        accessModes:
          - ReadWriteOnce
        {{- if $.node_vals.storageClassName }}
        storageClassName: {{ $.node_vals.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ default "15Gi" $.node_vals.storage_size }}
{{- if $.node_vals.service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.node_class }}-rpc
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
    - port: 80
      targetPort: 8732
      name: rpc
  selector:
    node_class: {{ $.node_class }}
  type: {{ $.node_vals.service.type }}
{{- end }}
{{- if $.node_vals.ingress }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.node_class }}
  namespace: {{ $.Release.Namespace }}
  annotations:
{{- $.node_vals.ingress.annotations | toYaml | nindent 4  }}
spec:
{{- if $.node_vals.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ $.node_vals.ingress.host }}
      secretName: {{ $.node_class }}-tls
{{- end }}
  rules:
    - host: {{ $.node_vals.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.node_class }}-rpc
                port:
                  name: rpc
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}
