{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
{{- toYaml .Values.serviceMonitor.labels | nindent 4 }}
  name: tezos-service-monitor
  namespace: {{ .Values.serviceMonitor.namespace }}
spec:
  endpoints:
  - interval: 15s
    port: metrics
    path: /metrics
  jobLabel: basenet
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      appType: octez-node
{{- end }}
