apiVersion: v1
kind: Service
metadata:
  name: tezos-node-rpc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 8732
      name: rpc
  {{- with .Values.services.tezos_node_rpc.selector | default (dict "appType" "tezos-node") }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  type: NodePort
---
{{- range $key, $val := .Values.nodes }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $key }}
  labels:
    appType: tezos-node
spec:
  ports:
    - port: 9732
      name: p2p
    - port: 9932
      name: metrics
  publishNotReadyAddresses: true
  clusterIP: None
  selector:
    node_class: {{ $key }}
---
{{- end }}
{{- if (include "tezos.shouldDeployTzktIndexer" .) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tzkt_indexer_statefulset.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 5000
  selector:
    app: {{ .Values.tzkt_indexer_statefulset.name }}
  type: ClusterIP
{{- if .Values.indexers.tzkt.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.tzkt_indexer_statefulset.name }}
  namespace: {{ $.Release.Namespace }}
  annotations:
{{- .Values.indexers.tzkt.ingress.annotations | toYaml | nindent 4 }}
spec:
{{- if .Values.indexers.tzkt.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.indexers.tzkt.ingress.host }}
      secretName: {{ .Values.tzkt_indexer_statefulset.name }}-tls
{{- end }}
  rules:
    - host: {{ .Values.indexers.tzkt.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.tzkt_indexer_statefulset.name }}
                port:
                  number: 5000
{{- end }}
{{- end }}
