# generated by datamodel-codegen:
<<<<<<< HEAD
#   filename:  pauseAllEntrypoints.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class PauseAllEntrypointsParameter(BaseModel):
    __root__: List[str]
=======
#   filename:  exit.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class ExitParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
>>>>>>> 63661dace (handlers refactored for dipdup 7)
