# generated by datamodel-codegen:
#   filename:  pauseAllEntrypoints.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class PauseAllEntrypointsParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
