# generated by datamodel-codegen:
#   filename:  propagateBreakGlass.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class PropagateBreakGlassParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
