# generated by datamodel-codegen:
#   filename:  removeBreakGlassControl.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class RemoveBreakGlassControlParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
