# generated by datamodel-codegen:
#   filename:  removeCouncilMember.json

from __future__ import annotations

from pydantic import BaseModel


class RemoveCouncilMemberParameter(BaseModel):
    __root__: str
