# generated by datamodel-codegen:
#   filename:  unpauseAllEntrypoints.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class UnpauseAllEntrypointsParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
